In [1]:
import numpy as np
import pandas as pd
import ast
from collections import defaultdict
import pymorphy3
from transformers import BertTokenizer, BertModel
import torch
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA
import plotly.express as px

C:\Users\topi7\OneDrive\Desktop\FEFU\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv("povarenok.csv")

In [3]:
df = df.drop(['url'], axis=1)

In [4]:
df

,name,ingredients
0,Густой молочно-клубничный коктейль,"{'Молоко': '250 мл', 'Клубника': '200 г', 'Сах..."
1,Рулетики,"{'Сыр твердый': None, 'Чеснок': None, 'Яйцо ку..."
2,"Салат ""Очищение души и кишечника""","{'Баклажан': '3 шт', 'Лук репчатый': '2 шт', '..."
3,Куриные котлеты с картофельным пюре в духовке,"{'Фарш куриный': '800 г', 'Пюре картофельное':..."
4,Рецепт вишневой наливки,"{'Вишня': '1 кг', 'Водка': '1 л', 'Сахар': '30..."
...,...,...
146577,"Украшение для блюд ""Снежинка""","{'Капуста краснокочанная': None, 'Капуста бело..."
146578,Греческий рисовый пирог с фаршем,"{'Фарш мясной': '400 г', 'Масло сливочное': '2..."
146579,Соус на груздях с хреном,"{'Грибы': '300 г', 'Чеснок': '5 зуб.', 'Лук ре..."
146580,Печенье со сливочным сыром,"{'Масло сливочное': '225 г', 'Сыр сливочный': ..."
146581,"Пирог ""Весенний"" с яблоками и апельсинами","{'Яйцо куриное': '4 шт', 'Сахар': '1 стак.', '..."

In [5]:
df['name'].notna().any()

True

In [6]:
df['ingredients'].notna().any()

True

In [7]:
# df = df[:10].copy()
df = df[:5800]

In [8]:
df['ingredients_dict'] = df['ingredients'].apply(ast.literal_eval)

C:\Users\topi7\AppData\Local\Temp\ipykernel_5956\1089393177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ingredients_dict'] = df['ingredients'].apply(ast.literal_eval)

In [9]:
df = df.drop(['ingredients'], axis=1)

In [10]:
df['ingredients_dict'] = df['ingredients_dict'].apply(lambda x: x.keys())

In [11]:
df

,name,ingredients_dict
0,Густой молочно-клубничный коктейль,"(Молоко, Клубника, Сахар)"
1,Рулетики,"(Сыр твердый, Чеснок, Яйцо куриное, Грейпфрут,..."
2,"Салат ""Очищение души и кишечника""","(Баклажан, Лук репчатый, Помидор, Чеснок, Соль..."
3,Куриные котлеты с картофельным пюре в духовке,"(Фарш куриный, Пюре картофельное, Желток яичны..."
4,Рецепт вишневой наливки,"(Вишня, Водка, Сахар, Кости, Корица, Гвоздика)"
...,...,...
5795,"Салат ""Для любимого мужчины""","(Горбуша, Картофель, Редис, Листья салата, Лук..."
5796,"Кускус ""На завтрак"" с орехами и сухофруктами","(Кус-кус, Курага, Чернослив, Орехи кешью, Орех..."
5797,"Блины ""Праздничные""","(Молоко, Яйцо куриное, Мука пшеничная, Масло п..."
5798,Кесо Фреско,"(Молоко, Закваска, Хлорид кальция, Сычужный фе..."
5799,Запеканка из кабачков,"(Кабачок, Лук репчатый, Фарш мясной, Яйцо кури..."

In [12]:
df['ingredients_dict'].notna().any()

True

In [13]:
df['ingredients_dict'] = df['ingredients_dict'].apply(lambda x: sorted(list(x)))

In [14]:
df['ingredients_list'] = df['ingredients_dict'].apply(
    lambda lst: [item.lower() for item in lst]
)

In [15]:
df = df.drop(['ingredients_dict'], axis=1)
df

,name,ingredients_list
0,Густой молочно-клубничный коктейль,"[клубника, молоко, сахар]"
1,Рулетики,"[грейпфрут, листья салата, лук зеленый, майоне..."
2,"Салат ""Очищение души и кишечника""","[баклажан, лук репчатый, майонез, перец черный..."
3,Куриные котлеты с картофельным пюре в духовке,"[желток яичный, зелень, лук репчатый, масло ра..."
4,Рецепт вишневой наливки,"[вишня, водка, гвоздика, корица, кости, сахар]"
...,...,...
5795,"Салат ""Для любимого мужчины""","[горбуша, картофель, листья салата, лук зелены..."
5796,"Кускус ""На завтрак"" с орехами и сухофруктами","[курага, кус-кус, масло сливочное, орехи грецк..."
5797,"Блины ""Праздничные""","[масло подсолнечное, масло сливочное, молоко, ..."
5798,Кесо Фреско,"[закваска, молоко, соль, сычужный фермент, хло..."
5799,Запеканка из кабачков,"[зелень, кабачок, лук репчатый, сыр копченый, ..."

## Лемматизация

In [16]:
morph = pymorphy3.MorphAnalyzer()

In [17]:
a = morph.parse('стали')[0]
a.normal_form

'стать'

In [18]:
df['ingredients_lemmatized'] = df['ingredients_list'].apply(
    lambda x: [morph.parse(i)[0].normal_form for i in x]
)

In [19]:
df

,name,ingredients_list,ingredients_lemmatized
0,Густой молочно-клубничный коктейль,"[клубника, молоко, сахар]","[клубника, молоко, сахар]"
1,Рулетики,"[грейпфрут, листья салата, лук зеленый, майоне...","[грейпфрут, листья салат, лук зелёный, майонез..."
2,"Салат ""Очищение души и кишечника""","[баклажан, лук репчатый, майонез, перец черный...","[баклажан, лук репчатый, майонез, перец чёрный..."
3,Куриные котлеты с картофельным пюре в духовке,"[желток яичный, зелень, лук репчатый, масло ра...","[желток яичный, зелень, лук репчатый, масло ра..."
4,Рецепт вишневой наливки,"[вишня, водка, гвоздика, корица, кости, сахар]","[вишня, водка, гвоздик, корица, кость, сахар]"
...,...,...,...
5795,"Салат ""Для любимого мужчины""","[горбуша, картофель, листья салата, лук зелены...","[горбуша, картофель, листья салат, лук зелёный..."
5796,"Кускус ""На завтрак"" с орехами и сухофруктами","[курага, кус-кус, масло сливочное, орехи грецк...","[курага, кус-кус, масло сливочный, орехи грецк..."
5797,"Блины ""Праздничные""","[масло подсолнечное, масло сливочное, молоко, ...","[масло подсолнечный, масло сливочный, молоко, ..."
5798,Кесо Фреско,"[закваска, молоко, соль, сычужный фермент, хло...","[закваска, молоко, соль, сычужный фермент, хло..."
5799,Запеканка из кабачков,"[зелень, кабачок, лук репчатый, сыр копченый, ...","[зелень, кабачок, лук репчатый, сыр копчёный, ..."

## Частотный анализ

In [20]:

all_ingredients = df['ingredients_lemmatized'].sum()

In [21]:
values, counts = np.unique(all_ingredients, return_counts=True)

In [22]:
frequency_analysis = dict(zip(values,counts ))

In [24]:
frequency_analysis = dict(sorted(frequency_analysis.items(), key=lambda item: item[1], reverse=True))

In [25]:
frequency_analysis

{'соль': 3125,
 'яйцо куриный': 2342,
 'мука пшеничный': 2046,
 'сахар': 1966,
 'лук репчатый': 1656,
 'масло растительный': 1573,
 'масло сливочный': 1526,
 'чеснок': 1229,
 'перец чёрный': 1131,
 'вода': 1019,
 'молоко': 955,
 'морковь': 898,
 'сметана': 750,
 'майонез': 690,
 'картофель': 647,
 'разрыхлитель тест': 631,
 'сыр твёрдый': 611,
 'помидор': 604,
 'масло оливковый': 532,
 'зелень': 530,
 'сливка': 490,
 'специя': 478,
 'соевый соусый': 468,
 'перец болгарский': 419,
 'дрожжи': 385,
 'сахарная пудрый': 371,
 'петрушка': 369,
 'сок лимонный': 363,
 'творог': 356,
 'мёд': 350,
 'уксус': 345,
 'укроп': 335,
 'яблоко': 332,
 'сода': 316,
 'рис': 307,
 'ванильный сахар': 305,
 'огурец': 295,
 'ванилин': 294,
 'корица': 283,
 'орехи грецкий': 276,
 'желток яичный': 272,
 'лимон': 271,
 'какао-порошок': 270,
 'лук зелёный': 256,
 'шампиньон': 240,
 'приправа': 237,
 'горчица': 234,
 'фарш мясной': 228,
 'масло подсолнечный': 225,
 'лист лавровый': 215,
 'гриб': 207,
 'томатная паста': 201,
 'кабачок': 194,
 'филе куриный': 192,
 'изюм': 184,
 'сахар коричневый': 183,
 'перец душистый': 175,
 'шоколад тёмный': 175,
 'имбирь': 171,
 'кунжут': 169,
 'баклажан': 163,
 'перец красный жгучий': 162,
 'желатина': 161,
 'паприка сладкий': 161,
 'бульон': 160,
 'свинина': 158,
 'кефир': 156,
 'крупа мать': 156,
 'маргарин': 156,
 'капуста белокочать': 155,
 'грудка куриный': 153,
 'йогурт': 149,
 'перец чили': 145,
 'белок яичный': 144,
 'молоко сгущенный': 144,
 'листья салат': 139,
 'базилик': 134,
 'крахмал': 133,
 'сухари панировочный': 133,
 'банан': 132,
 'тыква': 132,
 'миндаль': 131,
 'кукуруза': 125,
 'свёкла': 118,
 'цедра лимон': 118,
 'апельсин': 115,
 'курица': 112,
 'фасоль': 112,
 'кориандр': 110,
 'лук красный': 110,
 'кинза': 108,
 'хлеб': 108,
 'шоколад молочный': 108,
 'горошек зелёный': 105,
 'креветка': 104,
 'орех мускатный': 104,
 'вишня': 101,
 'мясо': 101,
 'рыба': 101,
 'соус': 98,
 'хлопья овсяной': 97,
 'говядина': 96,
 'кетчуп': 94,
 'стружка кокосовый': 93,
 'сыр голландский': 93,
 'помидоры черри': 90,
 'крахмал кукурузный': 86,
 'клубника': 84,
 'орех': 84,
 'мятый': 83,
 'сельдерей черешковый': 82,
 'колбаса': 80,
 'мак': 80,
 'печение': 80,
 'смесь перец': 80,
 'ветчина': 79,
 'вино белое сухой': 79,
 'чернослив': 79,
 'гвоздик': 78,
 'бекон': 76,
 'крабовые палочка': 76,
 'тимьян': 73,
 'сахар тростниковый': 72,
 'розмарин': 68,
 'крахмал картофельный': 67,
 'крупа гречневый': 67,
 'лук-порей': 66,
 'сыр плавленый': 66,
 'макаронные изделие': 65,
 'маслина': 64,
 'ананас': 63,
 'коньяк': 63,
 'шпинат': 62,
 'сыр творожный': 59,
 'тесто слоёный': 59,
 'варение': 58,
 'карри': 58,
 'куркума': 58,
 'курага': 56,
 'орегано': 55,
 'пармезан': 55,
 'тмин': 55,
 'шоколад белый': 55,
 'капуста цветный': 54,
 'цедра апельсина': 54,
 'груша': 53,
 'лук белый': 53,
 'оливки зелёный': 53,
 'сало': 53,
 'сода гашеная уксус': 53,
 'сок апельсиновый': 53,
 'капуста пекинский': 52,
 'перец сладкий': 52,
 'джема': 51,
 'клюква': 51,
 'сыр сливочный': 51,
 'кальмар': 50,
 'сыр мягкий': 50,
 'огурец мариновать': 49,
 'печень куриный': 48,
 'сельдь': 48,
 'филе рыбный': 47,
 'авокадо': 46,
 'орехи кедровый': 46,
 'перец сладкий красный': 46,
 'лаваш': 43,
 'моцарелла': 42,
 'перец белый': 42,
 'индейка': 41,
 'ликёр': 41,
 'окорочок куриный': 41,
 'батон': 40,
 'кофе растворимый': 40,
 'мука цельнозерновый': 40,
 'брокколи': 39,
 'кардамон': 39,
 'кислота лимонный': 39,
 'мука ржаной': 39,
 'малина': 38,
 'редис': 38,
 'сосиска': 38,
 'фасоль консервировать': 38,
 'чечевица': 38,
 'арахис': 37,
 'водка': 37,
 'ягода': 37,
 'брынза': 36,
 'порошок чесночный': 36,
 'киви': 35,
 'сок': 35,
 'сырок плавлёный': 35,
 'фарш куриный': 35,
 'ваниль': 34,
 'сухарик': 34,
 'бедро куриный': 33,
 'зира': 33,
 'персик': 33,
 'фасоль стручковый': 33,
 'хмель-сунель': 33,
 'цукат': 33,
 'абрикос': 32,
 'консервы рыбный': 32,
 'мука кукурузный': 32,
 'нут': 32,
 'слива': 32,
 'виноград': 31,
 'лосось': 31,
 'баранина': 30,
 'голень куриный': 30,
 'кофе натуральный': 30,
 'огурец солёный': 30,
 'тунец': 30,
 'фундук': 30,
 'грудинка': 29,
 'печень говяжий': 29,
 'ром': 29,
 'сёмга': 29,
 'томаты в собственном сока': 29,
 'вино красное сухой': 28,
 'закваска': 28,
 'мандарин': 28,
 'масло кунжутный': 28,
 'желе': 27,
 'краситель пищев': 27,
 'масло топлёный': 27,
 'посыпка кондитерский': 27,
 'смесь специя': 27,
 'сок томатный': 26,
 'шафран': 26,
 'крылья куриный': 25,
 'пшено': 25,
 'сыворотка': 25,
 'фет': 25,
 'брусника': 24,
 'лайм': 24,
 'овощ': 24,
 'соус-маринад': 24,
 'тесто слоеное бездрожжевой': 24,
 'финик': 24,
 'форель': 24,
 'хрен': 24,
 'крупа перловый': 23,
 'сельдерей корнев': 23,
 'семечки подсолнух': 23,
 'смородина черный': 23,
 'тесто дрожжевой': 23,
 'бальзамик': 22,
 'кус-кус': 22,
 'сыр полутвердый': 22,
 'телятина': 22,
 'цуккиня': 22,
 'яйцо перепелиный': 22,
 'икра красный': 21,
 'каперс': 21,
 'фрукт': 21,
 'блин': 20,
 'лапша': 20,
 'маскарпон': 20,
 'мороженое': 20,
 'оливки черный': 20,
 'отруби': 20,
 'тесто слоеное дрожжевой': 20,
 'чай чёрный': 20,
 'горбуша': 19,
 'руккола': 19,
 'семена льный': 19,
 'скумбрия': 19,
 'черника': 19,
 'гранат': 18,
 'кубик бульонный': 18,
 'лук-шалот': 18,
 'перец кайена': 18,
 'пиво светлый': 18,
 'сухофрукты': 18,
 'сыр адыгейский': 18,
 'сыр голуба': 18,
 'ванильная эссенция': 17,
 'горох': 17,
 'загуститель для сливка': 17,
 'капуста краснокочать': 17,
 'корж': 17,
 'пряность': 17,
 'щавель': 17,
 'аджика': 16,
 'мидия': 16,
 'молоко сухой': 16,
 'мука миндальный': 16,
 'мука рисовый': 16,
 'пудинг ванильный': 16,
 'сок свежевыжать': 16,
 'соус томатный': 16,
 'утка': 16,
 'фисташка': 16,
 'багет': 15,
 'глазурь': 15,
 'жир': 15,
 'колбаска': 15,
 'корнишон': 15,
 'кумина': 15,
 'ребра свиной': 15,
 'рикотт': 15,
 'сердечки куриный': 15,
 'спагетти': 15,
 'томаты вялёный': 15,
 'вода газировать': 14,
 'инжир': 14,
 'капуста квашеный': 14,
 'крем': 14,
 'мука овсяный': 14,
 'орехи кешью': 14,
 'редька': 14,
 'сухарь': 14,
 'уксусная эссенция': 14,
 'хлебец': 14,
 'майоран': 13,
 'молоко кокосовый': 13,
 'паста': 13,
 'сироп сахарный': 13,
 'смородина красный': 13,
 'сок яблочный': 13,
 'треск': 13,
 'вино белое полусладкий': 12,
 'капуста морский': 12,
 'коктейль морский': 12,
 'крекер': 12,
 'лёд': 12,
 'маршмеллоу': 12,
 'опёнок': 12,
 'рассол': 12,
 'сахар гранулировать': 12,
 'сердце': 12,
 'хлопья злаковый': 12,
 'черешня': 12,
 'айва': 11,
 'бадьян': 11,
 'булгур': 11,
 'конфета': 11,
 'кролик': 11,
 'семечки тыквенный': 11,
 'спаржа': 11,
 'фенхель': 11,
 'агар-агар': 10,
 'ассорти овощной': 10,
 'булка': 10,
 'вешенка': 10,
 'грейпфрут': 10,
 'ежевика': 10,
 'желудки куриный': 10,
 'лазание': 10,
 'лепёшка': 10,
 'мармелад': 10,
 'марципан': 10,
 'норь': 10,
 'перец зелёный': 10,
 'порошок пекарский': 10,
 'ряженка': 10,
 'сыр сулугуни': 10,
 'тоф': 10,
 'хлопья пшенный': 10,
 'шалфей': 10,
 'шпиг': 10,
 'язык говяжий': 10,
 'бисквит': 9,
 'вермишель': 9,
 'карп': 9,
 'квас': 9,
 'киноа': 9,
 'крабовое мясо': 9,
 'мука гречневый': 9,
 'рис дикий': 9,
 'рулька': 9,
 'семя': 9,
 'субпродукт': 9,
 'сыр колбасный': 9,
 'табаско': 9,
 'фарш индюшачий': 9,
 'хлопья гречневый': 9,
 'хлопья рисовый': 9,
 'шпрот': 9,
 'анчоус': 8,
 'ароматизатор': 8,
 'барбарис': 8,
 'булочка': 8,
 'вафля': 8,
 'вода минеральный': 8,
 'кишка': 8,
 'крупа кукурузный': 8,
 'мастика': 8,
 'пельмень': 8,
 'перец сладкий жёлтый': 8,
 'печень треска': 8,
 'пудинг': 8,
 'ревень': 8,
 'сироп фруктовый': 8,
 'сироп ягодный': 8,
 'соус ягодный': 8,
 'тарталетка': 8,
 'тесто фить': 8,
 'фунчоз': 8,
 'хлопья кукурузный': 8,
 'цыплёнок': 8,
 'анис': 7,
 'готовая начинка': 7,
 'грудка утиный': 7,
 'джем абрикосовый': 7,
 'икра рыбный': 7,
 'капуста китайский': 7,
 'конфитюр': 7,
 'крыжовник': 7,
 'манго': 7,
 'можжевельник': 7,
 'морепродукт': 7,
 'окорка': 7,
 'пектин': 7,
 'перец розовый': 7,
 'повидло': 7,
 'простокваша': 7,
 'пюре картофельный': 7,
 'пюре фруктовый': 7,
 'репа': 7,
 'семена горчица': 7,
 'сироп кленовый': 7,
 'сыр козий': 7,
 'творожная масса': 7,
 'фарш рыбный': 7,
 'чабёр': 7,
 'черемша': 7,
 'экстракт': 7,
 'эссенция': 7,
 'алкоголь': 6,
 'гребешок': 6,
 'гусь': 6,
 'дайкон': 6,
 'заменитель сахар': 6,
 'заправка': 6,
 'ириска': 6,
 'кокос': 6,
 'кость': 6,
 'крошка хлебный': 6,
 'масло кокосовый': 6,
 'мука льняной': 6,
 'орехи лесный': 6,
 'паштет': 6,
 'рисовая бумага': 6,
 'сайра': 6,
 'сок гранатовый': 6,
 'томаты протереть': 6,
 'хурма': 6,
 'эстрагон': 6,
 'ассорти фруктовый': 5,
 'ассорти ягодный': 5,
 'вино белое полусухой': 5,
 'вино красное полусладкий': 5,
 'вино рисовый': 5,
 'дичь': 5,
 'зефир': 5,
 'капуста брюссельский': 5,
 'капуста кольраби': 5,
 'каша': 5,
 'килька': 5,
 'корейка': 5,
 'лист виноградный': 5,
 'лист смородиновый': 5,
 'минтай': 5,
 'молоко топлёный': 5,
 'нектарин': 5,
 'паста шоколадный': 5,
 'пастернак': 5,
 'патиссон': 5,
 'перец сладкий зелёный': 5,
 'пюре овощной': 5,
 'пюре ягодный': 5,
 'сельдерей листовый': 5,
 'семечко': 5,
 'соль нитритный': 5,
 'тархун': 5,
 'тесто пельменный': 5,
 'чипсы': 5,
 'щука': 5,
 'язык свиной': 5,
 'батат': 4,
 'ботва': 4,
 'васаби': 4,
 'взбитые сливка': 4,
 'вино красное полусухой': 4,
 'гарам масать': 4,
 'грибы консервировать': 4,
 'икра чёрный': 4,
 'карамель': 4,
 'кожа куриный': 4,
 'компот': 4,
 'коренья': 4,
 'крапива': 4,
 'крупа пшеничный': 4,
 'лепесток': 4,
 'лечо': 4,
 'лист вишнёвый': 4,
 'маринад': 4,
 'масло кукурузный': 4,
 'масло тыквенный': 4,
 'маш': 4,
 'мука блинный': 4,
 'мука черёмуховый': 4,
 'мюсли': 4,
 'наршараб': 4,
 'паста арахисовый': 4,
 'пахта': 4,
 'печень свиный': 4,
 'пиво тёмный': 4,
 'пюре томатный': 4,
 'рак': 4,
 'ребра говяжий': 4,
 'ребро': 4,
 'смалец': 4,
 'сок ягодный': 4,
 'стружка шоколадный': 4,
 'сушка': 4,
 'сыр копчёный': 4,
 'сырок творожный': 4,
 'фрикаделька': 4,
 'фруктоза': 4,
 'цветок': 4,
 'шампанский': 4,
 'арбуз': 3,
 'бамия': 3,
 'безе': 3,
 'вино десертный': 3,
 'виски': 3,
 'глюкоза': 3,
 'драже': 3,
 'душица': 3,
 'дыня': 3,
 'капуста савойский': 3,
 'карбонад': 3,
 'масло арахисовый': 3,
 'масло грецкого орех': 3,
 'мойва': 3,
 'нога': 3,
 'облепиха': 3,
 'окунь морский': 3,
 'опара': 3,
 'осьминог': 3,
 'отвар': 3,
 'палтус': 3,
 'папоротник': 3,
 'паста кунжутный': 3,
 'патока': 3,
 'перец лимонный': 3,
 'песто': 3,
 'печень гусиный': 3,
 'пит': 3,
 'помело': 3,
 'порошок горчичный': 3,
 'пшеница': 3,
 'рапан': 3,
 'рябина черноплодный': 3,
 'сарделька': 3,
 'семолина': 3,
 'сироп ананасовый': 3,
 'соя': 3,
 'стрелки чесночный': 3,
 'тесто пресный': 3,
 'томаты пассеровать': 3,
 'урбечий': 3,
 'халва': 3,
 'хек': 3,
 'херес': 3,
 'чабрец': 3,
 'чай в пакетика': 3,
 'шелуха луковый': 3,
 'балык': 2,
 'бастурм': 2,
 'бешамель': 2,
 'боб': 2,
 'бренди': 2,
 'брюква': 2,
 'вино красное сладкий': 2,
 'вода розовый': 2,
 'голубика': 2,
 'гренка': 2,
 'грудка индюшка': 2,
 'детское питание': 2,
 'дорад': 2,
 'жидкий дый': 2,
 'земляника': 2,
 'какао тереть': 2,
 'калин': 2,
 'камбала': 2,
 'каннеллонить': 2,
 'кисель': 2,
 'клетчатка': 2,
 'кондитерское изделие': 2,
 'котлета': 2,
 'крем фреш': 2,
 'кресс-салат': 2,
 'кукурузные палочка': 2,
 'кумквата': 2,
 'кэроба': 2,
 'масло виноградной косточка': 2,
 'масло горчичный': 2,
 'масло льняный': 2,
 'матч': 2,
 'молоко концентрировать': 2,
 'морской язык': 2,
 'мука нутовый': 2,
 'мясо криль': 2,
 'окунь': 2,
 'пажитник': 2,
 'пангасиус': 2,
 'паста карри': 2,
 'паста сахарный': 2,
 'паста тахинный': 2,
 'перец сычуаньский': 2,
 'печень индюшиный': 2,
 'пряник': 2,
 'росток': 2,
 'рулет': 2,
 'рябина красный': 2,
 'салями': 2,
 'сироп ванильный': 2,
 'сироп глюкоза': 2,
 'сироп персиковый': 2,
 'сок морковный': 2,
 'соус устричный': 2,
 'спирт': 2,
 'суповой набор': 2,
 'сухой завтрак': 2,
 'сычужный фермент': 2,
 'тилапий': 2,
 'ткемали': 2,
 'тост': 2,
 'тушёнка': 2,
 'уцхо-сунеля': 2,
 'физалис': 2,
 'филе': 2,
 'хлорид кальция': 2,
 'цедра лайм': 2,
 'черёмуха': 2,
 'шейка свиный': 2,
 'шнитта-лука': 2,
 'алыча': 1,
 'аммоний пищев': 1,
 'артишок': 1,
 'ассорти мясной': 1,
 'барабулька': 1,
 'белорыбица': 1,
 'буженина': 1,
 'ванильный стручок': 1,
 'вермут': 1,
 'вино розовое полусухой': 1,
 'вода цветочная апельсиновый': 1,
 'водоросль': 1,
 'глутамат натрия': 1,
 'джем апельсиновый': 1,
 'джусать': 1,
 'желирующая смесь': 1,
 'желудок': 1,
 'зерно': 1,
 'зубатка': 1,
 'икра минтай': 1,
 'икра овощной': 1,
 'какао-масло': 1,
 'какао-напиток': 1,
 'капучиный': 1,
 'каракатица': 1,
 'карась': 1,
 'каркад': 1,
 'катык': 1,
 'каштан': 1,
 'кета': 1,
 'кижучий': 1,
 'кожа рыбный': 1,
 'концентрат': 1,
 'кора дуб': 1,
 'крошка вафельный': 1,
 'крупа овсяной': 1,
 'крупа ячневый': 1,
 'лен': 1,
 'лимонад': 1,
 'лимонная трава': 1,
 'лимонник': 1,
 'лист капустный': 1,
 'лист цветочный': 1,
 'личить': 1,
 'масло миндальный': 1,
 'масло рапсовый': 1,
 'масло соевой': 1,
 'масло шоколадный': 1,
 'маслёнок': 1,
 'маца': 1,
 'мацони': 1,
 'мелисса': 1,
 'мисо-паста': 1,
 'молоко миндальный': 1,
 'мука конопляный': 1,
 'мука кунжутный': 1,
 'мука ячменный': 1,
 'налим': 1,
 'напиток кисломолочный': 1,
 'напиток молочный': 1,
 'нога бараний': 1,
 'нутелла': 1,
 'овёс': 1,
 'орехи бразильский': 1,
 'орехи пекан': 1,
 'папайя': 1,
 'паста ореховой': 1,
 'паста перечный': 1,
 'пастила': 1,
 'пенна': 1,
 'перепел': 1,
 'перец пепперони': 1,
 'перец ямайский': 1,
 'печень барание': 1,
 'полба': 1,
 'помидор мариновать': 1,
 'порошок томатный': 1,
 'потроха': 1,
 'пралине': 1,
 'пресервы': 1,
 'пудинг карамельный': 1,
 'ракушка': 1,
 'рис воздушный': 1,
 'рис коричневый': 1,
 'рожок': 1,
 'романо': 1,
 'рябчик': 1,
 'салака': 1,
 'сахар кусков': 1,
 'сахар-рафинад': 1,
 'семена укроп': 1,
 'сидр': 1,
 'сироп инвертный': 1,
 'сироп клубничный': 1,
 'сироп лимонный': 1,
 'сироп мятный': 1,
 'смесь молочный': 1,
 'смесь порошковый': 1,
 'соевые проростка': 1,
 'сок берёзовый': 1,
 'солод': 1,
 'соломка': 1,
 'соус майонезный': 1,
 'соус фруктовый': 1,
 'сумах': 1,
 'сусло квасный': 1,
 'тандури масать': 1,
 'тапиока': 1,
 'текила': 1,
 'тесто песочный': 1,
 'толокно': 1,
 'томаты сушеный': 1,
 'тоник': 1,
 'угорь': 1,
 'урюк': 1,
 'фарш соевый': 1,
 'фейхоа': 1,
 'фетаки': 1,
 'фритюр': 1,
 'хвост': 1,
 'хлебобулочные изделие': 1,
 'хлопья картофельный': 1,
 'цедра грейпфрут': 1,
 'цедра мандарин': 1,
 'цесарка': 1,
 'цикорий': 1,
 'чай зелёный': 1,
 'шейка куриный': 1,
 'шиповник': 1,
 'эклер': 1,
 'ёрш': 1}

## BOW

In [26]:
# unique_ingredients = sorted(set(all_ingredients))
# df['BOW'] = df['ingredients_lemmatized'].apply(lambda x: [int(i in x) for i in unique_ingredients])
# df['BOW']

In [27]:
exploded = df.explode('ingredients_lemmatized')

In [28]:
dummies  = pd.get_dummies(exploded['ingredients_lemmatized'])

In [29]:
bow = dummies.groupby(exploded.index).max()

In [30]:
bow

,абрикос,авокадо,агар-агар,аджика,айва,алкоголь,алыча,аммоний пищев,ананас,анис,...,экстракт,эссенция,эстрагон,яблоко,ягода,язык говяжий,язык свиной,яйцо куриный,яйцо перепелиный,ёрш
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5795,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5796,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5797,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5798,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5799,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

## BPE

In [31]:
corpus = []

for idx, ingredient in enumerate(frequency_analysis):
    a = []
    for i in ingredient:
        if i ==' ':
            a.append('</w>')
        else:
            a.append(i)
    a.append('</w>')
    corpus.append(a)
    corpus[idx].append(int(frequency_analysis[ingredient]))

In [32]:
corpus

[['с', 'о', 'л', 'ь', '</w>', 3125],
 ['я', 'й', 'ц', 'о', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й', '</w>', 2342],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'п',
  'ш',
  'е',
  'н',
  'и',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  2046],
 ['с', 'а', 'х', 'а', 'р', '</w>', 1966],
 ['л', 'у', 'к', '</w>', 'р', 'е', 'п', 'ч', 'а', 'т', 'ы', 'й', '</w>', 1656],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'р',
  'а',
  'с',
  'т',
  'и',
  'т',
  'е',
  'л',
  'ь',
  'н',
  'ы',
  'й',
  '</w>',
  1573],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'с',
  'л',
  'и',
  'в',
  'о',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  1526],
 ['ч', 'е', 'с', 'н', 'о', 'к', '</w>', 1229],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'ч', 'ё', 'р', 'н', 'ы', 'й', '</w>', 1131],
 ['в', 'о', 'д', 'а', '</w>', 1019],
 ['м', 'о', 'л', 'о', 'к', 'о', '</w>', 955],
 ['м', 'о', 'р', 'к', 'о', 'в', 'ь', '</w>', 898],
 ['с', 'м', 'е', 'т', 'а', 'н', 'а', '</w>', 750],
 ['м', 'а', 'й', 'о', 'н', 'е', 'з', '</w>', 690],
 ['к', 'а', 'р', 'т', 'о', 'ф', 'е', 'л', 'ь', '</w>', 647],
 ['р',
  'а',
  'з',
  'р',
  'ы',
  'х',
  'л',
  'и',
  'т',
  'е',
  'л',
  'ь',
  '</w>',
  'т',
  'е',
  'с',
  'т',
  '</w>',
  631],
 ['с', 'ы', 'р', '</w>', 'т', 'в', 'ё', 'р', 'д', 'ы', 'й', '</w>', 611],
 ['п', 'о', 'м', 'и', 'д', 'о', 'р', '</w>', 604],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'о',
  'л',
  'и',
  'в',
  'к',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  532],
 ['з', 'е', 'л', 'е', 'н', 'ь', '</w>', 530],
 ['с', 'л', 'и', 'в', 'к', 'а', '</w>', 490],
 ['с', 'п', 'е', 'ц', 'и', 'я', '</w>', 478],
 ['с',
  'о',
  'е',
  'в',
  'ы',
  'й',
  '</w>',
  'с',
  'о',
  'у',
  'с',
  'ы',
  'й',
  '</w>',
  468],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'б',
  'о',
  'л',
  'г',
  'а',
  'р',
  'с',
  'к',
  'и',
  'й',
  '</w>',
  419],
 ['д', 'р', 'о', 'ж', 'ж', 'и', '</w>', 385],
 ['с',
  'а',
  'х',
  'а',
  'р',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'у',
  'д',
  'р',
  'ы',
  'й',
  '</w>',
  371],
 ['п', 'е', 'т', 'р', 'у', 'ш', 'к', 'а', '</w>', 369],
 ['с', 'о', 'к', '</w>', 'л', 'и', 'м', 'о', 'н', 'н', 'ы', 'й', '</w>', 363],
 ['т', 'в', 'о', 'р', 'о', 'г', '</w>', 356],
 ['м', 'ё', 'д', '</w>', 350],
 ['у', 'к', 'с', 'у', 'с', '</w>', 345],
 ['у', 'к', 'р', 'о', 'п', '</w>', 335],
 ['я', 'б', 'л', 'о', 'к', 'о', '</w>', 332],
 ['с', 'о', 'д', 'а', '</w>', 316],
 ['р', 'и', 'с', '</w>', 307],
 ['в',
  'а',
  'н',
  'и',
  'л',
  'ь',
  'н',
  'ы',
  'й',
  '</w>',
  'с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  305],
 ['о', 'г', 'у', 'р', 'е', 'ц', '</w>', 295],
 ['в', 'а', 'н', 'и', 'л', 'и', 'н', '</w>', 294],
 ['к', 'о', 'р', 'и', 'ц', 'а', '</w>', 283],
 ['о',
  'р',
  'е',
  'х',
  'и',
  '</w>',
  'г',
  'р',
  'е',
  'ц',
  'к',
  'и',
  'й',
  '</w>',
  276],
 ['ж',
  'е',
  'л',
  'т',
  'о',
  'к',
  '</w>',
  'я',
  'и',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  272],
 ['л', 'и', 'м', 'о', 'н', '</w>', 271],
 ['к',
  'а',
  'к',
  'а',
  'о',
  '-',
  'п',
  'о',
  'р',
  'о',
  'ш',
  'о',
  'к',
  '</w>',
  270],
 ['л', 'у', 'к', '</w>', 'з', 'е', 'л', 'ё', 'н', 'ы', 'й', '</w>', 256],
 ['ш', 'а', 'м', 'п', 'и', 'н', 'ь', 'о', 'н', '</w>', 240],
 ['п', 'р', 'и', 'п', 'р', 'а', 'в', 'а', '</w>', 237],
 ['г', 'о', 'р', 'ч', 'и', 'ц', 'а', '</w>', 234],
 ['ф', 'а', 'р', 'ш', '</w>', 'м', 'я', 'с', 'н', 'о', 'й', '</w>', 228],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'п',
  'о',
  'д',
  'с',
  'о',
  'л',
  'н',
  'е',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  225],
 ['л',
  'и',
  'с',
  'т',
  '</w>',
  'л',
  'а',
  'в',
  'р',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  215],
 ['г', 'р', 'и', 'б', '</w>', 207],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'а',
  'с',
  'т',
  'а',
  '</w>',
  201],
 ['к', 'а', 'б', 'а', 'ч', 'о', 'к', '</w>', 194],
 ['ф', 'и', 'л', 'е', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й', '</w>', 192],
 ['и', 'з', 'ю', 'м', '</w>', 184],
 ['с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  'к',
  'о',
  'р',
  'и',
  'ч',
  'н',
  'е',
  'в',
  'ы',
  'й',
  '</w>',
  183],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'д',
  'у',
  'ш',
  'и',
  'с',
  'т',
  'ы',
  'й',
  '</w>',
  175],
 ['ш',
  'о',
  'к',
  'о',
  'л',
  'а',
  'д',
  '</w>',
  'т',
  'ё',
  'м',
  'н',
  'ы',
  'й',
  '</w>',
  175],
 ['и', 'м', 'б', 'и', 'р', 'ь', '</w>', 171],
 ['к', 'у', 'н', 'ж', 'у', 'т', '</w>', 169],
 ['б', 'а', 'к', 'л', 'а', 'ж', 'а', 'н', '</w>', 163],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'ы',
  'й',
  '</w>',
  'ж',
  'г',
  'у',
  'ч',
  'и',
  'й',
  '</w>',
  162],
 ['ж', 'е', 'л', 'а', 'т', 'и', 'н', 'а', '</w>', 161],
 ['п',
  'а',
  'п',
  'р',
  'и',
  'к',
  'а',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й',
  '</w>',
  161],
 ['б', 'у', 'л', 'ь', 'о', 'н', '</w>', 160],
 ['с', 'в', 'и', 'н', 'и', 'н', 'а', '</w>', 158],
 ['к', 'е', 'ф', 'и', 'р', '</w>', 156],
 ['к', 'р', 'у', 'п', 'а', '</w>', 'м', 'а', 'т', 'ь', '</w>', 156],
 ['м', 'а', 'р', 'г', 'а', 'р', 'и', 'н', '</w>', 156],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'б',
  'е',
  'л',
  'о',
  'к',
  'о',
  'ч',
  'а',
  'т',
  'ь',
  '</w>',
  155],
 ['г',
  'р',
  'у',
  'д',
  'к',
  'а',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  153],
 ['й', 'о', 'г', 'у', 'р', 'т', '</w>', 149],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'ч', 'и', 'л', 'и', '</w>', 145],
 ['б', 'е', 'л', 'о', 'к', '</w>', 'я', 'и', 'ч', 'н', 'ы', 'й', '</w>', 144],
 ['м',
  'о',
  'л',
  'о',
  'к',
  'о',
  '</w>',
  'с',
  'г',
  'у',
  'щ',
  'е',
  'н',
  'н',
  'ы',
  'й',
  '</w>',
  144],
 ['л', 'и', 'с', 'т', 'ь', 'я', '</w>', 'с', 'а', 'л', 'а', 'т', '</w>', 139],
 ['б', 'а', 'з', 'и', 'л', 'и', 'к', '</w>', 134],
 ['к', 'р', 'а', 'х', 'м', 'а', 'л', '</w>', 133],
 ['с',
  'у',
  'х',
  'а',
  'р',
  'и',
  '</w>',
  'п',
  'а',
  'н',
  'и',
  'р',
  'о',
  'в',
  'о',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  133],
 ['б', 'а', 'н', 'а', 'н', '</w>', 132],
 ['т', 'ы', 'к', 'в', 'а', '</w>', 132],
 ['м', 'и', 'н', 'д', 'а', 'л', 'ь', '</w>', 131],
 ['к', 'у', 'к', 'у', 'р', 'у', 'з', 'а', '</w>', 125],
 ['с', 'в', 'ё', 'к', 'л', 'а', '</w>', 118],
 ['ц', 'е', 'д', 'р', 'а', '</w>', 'л', 'и', 'м', 'о', 'н', '</w>', 118],
 ['а', 'п', 'е', 'л', 'ь', 'с', 'и', 'н', '</w>', 115],
 ['к', 'у', 'р', 'и', 'ц', 'а', '</w>', 112],
 ['ф', 'а', 'с', 'о', 'л', 'ь', '</w>', 112],
 ['к', 'о', 'р', 'и', 'а', 'н', 'д', 'р', '</w>', 110],
 ['л', 'у', 'к', '</w>', 'к', 'р', 'а', 'с', 'н', 'ы', 'й', '</w>', 110],
 ['к', 'и', 'н', 'з', 'а', '</w>', 108],
 ['х', 'л', 'е', 'б', '</w>', 108],
 ['ш',
  'о',
  'к',
  'о',
  'л',
  'а',
  'д',
  '</w>',
  'м',
  'о',
  'л',
  'о',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  108],
 ['г',
  'о',
  'р',
  'о',
  'ш',
  'е',
  'к',
  '</w>',
  'з',
  'е',
  'л',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  105],
 ['к', 'р', 'е', 'в', 'е', 'т', 'к', 'а', '</w>', 104],
 ['о',
  'р',
  'е',
  'х',
  '</w>',
  'м',
  'у',
  'с',
  'к',
  'а',
  'т',
  'н',
  'ы',
  'й',
  '</w>',
  104],
 ['в', 'и', 'ш', 'н', 'я', '</w>', 101],
 ['м', 'я', 'с', 'о', '</w>', 101],
 ['р', 'ы', 'б', 'а', '</w>', 101],
 ['с', 'о', 'у', 'с', '</w>', 98],
 ['х',
  'л',
  'о',
  'п',
  'ь',
  'я',
  '</w>',
  'о',
  'в',
  'с',
  'я',
  'н',
  'о',
  'й',
  '</w>',
  97],
 ['г', 'о', 'в', 'я', 'д', 'и', 'н', 'а', '</w>', 96],
 ['к', 'е', 'т', 'ч', 'у', 'п', '</w>', 94],
 ['с',
  'т',
  'р',
  'у',
  'ж',
  'к',
  'а',
  '</w>',
  'к',
  'о',
  'к',
  'о',
  'с',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  93],
 ['с',
  'ы',
  'р',
  '</w>',
  'г',
  'о',
  'л',
  'л',
  'а',
  'н',
  'д',
  'с',
  'к',
  'и',
  'й',
  '</w>',
  93],
 ['п',
  'о',
  'м',
  'и',
  'д',
  'о',
  'р',
  'ы',
  '</w>',
  'ч',
  'е',
  'р',
  'р',
  'и',
  '</w>',
  90],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'у',
  'к',
  'у',
  'р',
  'у',
  'з',
  'н',
  'ы',
  'й',
  '</w>',
  86],
 ['к', 'л', 'у', 'б', 'н', 'и', 'к', 'а', '</w>', 84],
 ['о', 'р', 'е', 'х', '</w>', 84],
 ['м', 'я', 'т', 'ы', 'й', '</w>', 83],
 ['с',
  'е',
  'л',
  'ь',
  'д',
  'е',
  'р',
  'е',
  'й',
  '</w>',
  'ч',
  'е',
  'р',
  'е',
  'ш',
  'к',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  82],
 ['к', 'о', 'л', 'б', 'а', 'с', 'а', '</w>', 80],
 ['м', 'а', 'к', '</w>', 80],
 ['п', 'е', 'ч', 'е', 'н', 'и', 'е', '</w>', 80],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'п', 'е', 'р', 'е', 'ц', '</w>', 80],
 ['в', 'е', 'т', 'ч', 'и', 'н', 'а', '</w>', 79],
 ['в',
  'и',
  'н',
  'о',
  '</w>',
  'б',
  'е',
  'л',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й',
  '</w>',
  79],
 ['ч', 'е', 'р', 'н', 'о', 'с', 'л', 'и', 'в', '</w>', 79],
 ['г', 'в', 'о', 'з', 'д', 'и', 'к', '</w>', 78],
 ['б', 'е', 'к', 'о', 'н', '</w>', 76],
 ['к',
  'р',
  'а',
  'б',
  'о',
  'в',
  'ы',
  'е',
  '</w>',
  'п',
  'а',
  'л',
  'о',
  'ч',
  'к',
  'а',
  '</w>',
  76],
 ['т', 'и', 'м', 'ь', 'я', 'н', '</w>', 73],
 ['с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  'т',
  'р',
  'о',
  'с',
  'т',
  'н',
  'и',
  'к',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  72],
 ['р', 'о', 'з', 'м', 'а', 'р', 'и', 'н', '</w>', 68],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'а',
  'р',
  'т',
  'о',
  'ф',
  'е',
  'л',
  'ь',
  'н',
  'ы',
  'й',
  '</w>',
  67],
 ['к',
  'р',
  'у',
  'п',
  'а',
  '</w>',
  'г',
  'р',
  'е',
  'ч',
  'н',
  'е',
  'в',
  'ы',
  'й',
  '</w>',
  67],
 ['л', 'у', 'к', '-', 'п', 'о', 'р', 'е', 'й', '</w>', 66],
 ['с',
  'ы',
  'р',
  '</w>',
  'п',
  'л',
  'а',
  'в',
  'л',
  'е',
  'н',
  'ы',
  'й',
  '</w>',
  66],
 ['м',
  'а',
  'к',
  'а',
  'р',
  'о',
  'н',
  'н',
  'ы',
  'е',
  '</w>',
  'и',
  'з',
  'д',
  'е',
  'л',
  'и',
  'е',
  '</w>',
  65],
 ['м', 'а', 'с', 'л', 'и', 'н', 'а', '</w>', 64],
 ['а', 'н', 'а', 'н', 'а', 'с', '</w>', 63],
 ['к', 'о', 'н', 'ь', 'я', 'к', '</w>', 63],
 ['ш', 'п', 'и', 'н', 'а', 'т', '</w>', 62],
 ['с',
  'ы',
  'р',
  '</w>',
  'т',
  'в',
  'о',
  'р',
  'о',
  'ж',
  'н',
  'ы',
  'й',
  '</w>',
  59],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'с',
  'л',
  'о',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  59],
 ['в', 'а', 'р', 'е', 'н', 'и', 'е', '</w>', 58],
 ['к', 'а', 'р', 'р', 'и', '</w>', 58],
 ['к', 'у', 'р', 'к', 'у', 'м', 'а', '</w>', 58],
 ['к', 'у', 'р', 'а', 'г', 'а', '</w>', 56],
 ['о', 'р', 'е', 'г', 'а', 'н', 'о', '</w>', 55],
 ['п', 'а', 'р', 'м', 'е', 'з', 'а', 'н', '</w>', 55],
 ['т', 'м', 'и', 'н', '</w>', 55],
 ['ш',
  'о',
  'к',
  'о',
  'л',
  'а',
  'д',
  '</w>',
  'б',
  'е',
  'л',
  'ы',
  'й',
  '</w>',
  55],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'ц',
  'в',
  'е',
  'т',
  'н',
  'ы',
  'й',
  '</w>',
  54],
 ['ц',
  'е',
  'д',
  'р',
  'а',
  '</w>',
  'а',
  'п',
  'е',
  'л',
  'ь',
  'с',
  'и',
  'н',
  'а',
  '</w>',
  54],
 ['г', 'р', 'у', 'ш', 'а', '</w>', 53],
 ['л', 'у', 'к', '</w>', 'б', 'е', 'л', 'ы', 'й', '</w>', 53],
 ['о',
  'л',
  'и',
  'в',
  'к',
  'и',
  '</w>',
  'з',
  'е',
  'л',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  53],
 ['с', 'а', 'л', 'о', '</w>', 53],
 ['с',
  'о',
  'д',
  'а',
  '</w>',
  'г',
  'а',
  'ш',
  'е',
  'н',
  'а',
  'я',
  '</w>',
  'у',
  'к',
  'с',
  'у',
  'с',
  '</w>',
  53],
 ['с',
  'о',
  'к',
  '</w>',
  'а',
  'п',
  'е',
  'л',
  'ь',
  'с',
  'и',
  'н',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  53],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'п',
  'е',
  'к',
  'и',
  'н',
  'с',
  'к',
  'и',
  'й',
  '</w>',
  52],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й',
  '</w>',
  52],
 ['д', 'ж', 'е', 'м', 'а', '</w>', 51],
 ['к', 'л', 'ю', 'к', 'в', 'а', '</w>', 51],
 ['с',
  'ы',
  'р',
  '</w>',
  'с',
  'л',
  'и',
  'в',
  'о',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  51],
 ['к', 'а', 'л', 'ь', 'м', 'а', 'р', '</w>', 50],
 ['с', 'ы', 'р', '</w>', 'м', 'я', 'г', 'к', 'и', 'й', '</w>', 50],
 ['о',
  'г',
  'у',
  'р',
  'е',
  'ц',
  '</w>',
  'м',
  'а',
  'р',
  'и',
  'н',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  49],
 ['п',
  'е',
  'ч',
  'е',
  'н',
  'ь',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  48],
 ['с', 'е', 'л', 'ь', 'д', 'ь', '</w>', 48],
 ['ф', 'и', 'л', 'е', '</w>', 'р', 'ы', 'б', 'н', 'ы', 'й', '</w>', 47],
 ['а', 'в', 'о', 'к', 'а', 'д', 'о', '</w>', 46],
 ['о',
  'р',
  'е',
  'х',
  'и',
  '</w>',
  'к',
  'е',
  'д',
  'р',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  46],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й',
  '</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'ы',
  'й',
  '</w>',
  46],
 ['л', 'а', 'в', 'а', 'ш', '</w>', 43],
 ['м', 'о', 'ц', 'а', 'р', 'е', 'л', 'л', 'а', '</w>', 42],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'б', 'е', 'л', 'ы', 'й', '</w>', 42],
 ['и', 'н', 'д', 'е', 'й', 'к', 'а', '</w>', 41],
 ['л', 'и', 'к', 'ё', 'р', '</w>', 41],
 ['о',
  'к',
  'о',
  'р',
  'о',
  'ч',
  'о',
  'к',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  41],
 ['б', 'а', 'т', 'о', 'н', '</w>', 40],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'р',
  'а',
  'с',
  'т',
  'в',
  'о',
  'р',
  'и',
  'м',
  'ы',
  'й',
  '</w>',
  40],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'ц',
  'е',
  'л',
  'ь',
  'н',
  'о',
  'з',
  'е',
  'р',
  'н',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  40],
 ['б', 'р', 'о', 'к', 'к', 'о', 'л', 'и', '</w>', 39],
 ['к', 'а', 'р', 'д', 'а', 'м', 'о', 'н', '</w>', 39],
 ['к',
  'и',
  'с',
  'л',
  'о',
  'т',
  'а',
  '</w>',
  'л',
  'и',
  'м',
  'о',
  'н',
  'н',
  'ы',
  'й',
  '</w>',
  39],
 ['м', 'у', 'к', 'а', '</w>', 'р', 'ж', 'а', 'н', 'о', 'й', '</w>', 39],
 ['м', 'а', 'л', 'и', 'н', 'а', '</w>', 38],
 ['р', 'е', 'д', 'и', 'с', '</w>', 38],
 ['с', 'о', 'с', 'и', 'с', 'к', 'а', '</w>', 38],
 ['ф',
  'а',
  'с',
  'о',
  'л',
  'ь',
  '</w>',
  'к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'и',
  'р',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  38],
 ['ч', 'е', 'ч', 'е', 'в', 'и', 'ц', 'а', '</w>', 38],
 ['а', 'р', 'а', 'х', 'и', 'с', '</w>', 37],
 ['в', 'о', 'д', 'к', 'а', '</w>', 37],
 ['я', 'г', 'о', 'д', 'а', '</w>', 37],
 ['б', 'р', 'ы', 'н', 'з', 'а', '</w>', 36],
 ['п',
  'о',
  'р',
  'о',
  'ш',
  'о',
  'к',
  '</w>',
  'ч',
  'е',
  'с',
  'н',
  'о',
  'ч',
  'н',
  'ы',
  'й',
  '</w>',
  36],
 ['к', 'и', 'в', 'и', '</w>', 35],
 ['с', 'о', 'к', '</w>', 35],
 ['с',
  'ы',
  'р',
  'о',
  'к',
  '</w>',
  'п',
  'л',
  'а',
  'в',
  'л',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  35],
 ['ф', 'а', 'р', 'ш', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й', '</w>', 35],
 ['в', 'а', 'н', 'и', 'л', 'ь', '</w>', 34],
 ['с', 'у', 'х', 'а', 'р', 'и', 'к', '</w>', 34],
 ['б',
  'е',
  'д',
  'р',
  'о',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  33],
 ['з', 'и', 'р', 'а', '</w>', 33],
 ['п', 'е', 'р', 'с', 'и', 'к', '</w>', 33],
 ['ф',
  'а',
  'с',
  'о',
  'л',
  'ь',
  '</w>',
  'с',
  'т',
  'р',
  'у',
  'ч',
  'к',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  33],
 ['х', 'м', 'е', 'л', 'ь', '-', 'с', 'у', 'н', 'е', 'л', 'ь', '</w>', 33],
 ['ц', 'у', 'к', 'а', 'т', '</w>', 33],
 ['а', 'б', 'р', 'и', 'к', 'о', 'с', '</w>', 32],
 ['к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'ы',
  '</w>',
  'р',
  'ы',
  'б',
  'н',
  'ы',
  'й',
  '</w>',
  32],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'к',
  'у',
  'к',
  'у',
  'р',
  'у',
  'з',
  'н',
  'ы',
  'й',
  '</w>',
  32],
 ['н', 'у', 'т', '</w>', 32],
 ['с', 'л', 'и', 'в', 'а', '</w>', 32],
 ['в', 'и', 'н', 'о', 'г', 'р', 'а', 'д', '</w>', 31],
 ['л', 'о', 'с', 'о', 'с', 'ь', '</w>', 31],
 ['б', 'а', 'р', 'а', 'н', 'и', 'н', 'а', '</w>', 30],
 ['г',
  'о',
  'л',
  'е',
  'н',
  'ь',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  30],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'н',
  'а',
  'т',
  'у',
  'р',
  'а',
  'л',
  'ь',
  'н',
  'ы',
  'й',
  '</w>',
  30],
 ['о',
  'г',
  'у',
  'р',
  'е',
  'ц',
  '</w>',
  'с',
  'о',
  'л',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  30],
 ['т', 'у', 'н', 'е', 'ц', '</w>', 30],
 ['ф', 'у', 'н', 'д', 'у', 'к', '</w>', 30],
 ['г', 'р', 'у', 'д', 'и', 'н', 'к', 'а', '</w>', 29],
 ['п',
  'е',
  'ч',
  'е',
  'н',
  'ь',
  '</w>',
  'г',
  'о',
  'в',
  'я',
  'ж',
  'и',
  'й',
  '</w>',
  29],
 ['р', 'о', 'м', '</w>', 29],
 ['с', 'ё', 'м', 'г', 'а', '</w>', 29],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'ы',
  '</w>',
  'в',
  '</w>',
  'с',
  'о',
  'б',
  'с',
  'т',
  'в',
  'е',
  'н',
  'н',
  'о',
  'м',
  '</w>',
  'с',
  'о',
  'к',
  'а',
  '</w>',
  29],
 ['в',
  'и',
  'н',
  'о',
  '</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й',
  '</w>',
  28],
 ['з', 'а', 'к', 'в', 'а', 'с', 'к', 'а', '</w>', 28],
 ['м', 'а', 'н', 'д', 'а', 'р', 'и', 'н', '</w>', 28],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'к',
  'у',
  'н',
  'ж',
  'у',
  'т',
  'н',
  'ы',
  'й',
  '</w>',
  28],
 ['ж', 'е', 'л', 'е', '</w>', 27],
 ['к',
  'р',
  'а',
  'с',
  'и',
  'т',
  'е',
  'л',
  'ь',
  '</w>',
  'п',
  'и',
  'щ',
  'е',
  'в',
  '</w>',
  27],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'т',
  'о',
  'п',
  'л',
  'ё',
  'н',
  'ы',
  'й',
  '</w>',
  27],
 ['п',
  'о',
  'с',
  'ы',
  'п',
  'к',
  'а',
  '</w>',
  'к',
  'о',
  'н',
  'д',
  'и',
  'т',
  'е',
  'р',
  'с',
  'к',
  'и',
  'й',
  '</w>',
  27],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'с', 'п', 'е', 'ц', 'и', 'я', '</w>', 27],
 ['с', 'о', 'к', '</w>', 'т', 'о', 'м', 'а', 'т', 'н', 'ы', 'й', '</w>', 26],
 ['ш', 'а', 'ф', 'р', 'а', 'н', '</w>', 26],
 ['к',
  'р',
  'ы',
  'л',
  'ь',
  'я',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  25],
 ['п', 'ш', 'е', 'н', 'о', '</w>', 25],
 ['с', 'ы', 'в', 'о', 'р', 'о', 'т', 'к', 'а', '</w>', 25],
 ['ф', 'е', 'т', '</w>', 25],
 ['б', 'р', 'у', 'с', 'н', 'и', 'к', 'а', '</w>', 24],
 ['л', 'а', 'й', 'м', '</w>', 24],
 ['о', 'в', 'о', 'щ', '</w>', 24],
 ['с', 'о', 'у', 'с', '-', 'м', 'а', 'р', 'и', 'н', 'а', 'д', '</w>', 24],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'с',
  'л',
  'о',
  'е',
  'н',
  'о',
  'е',
  '</w>',
  'б',
  'е',
  'з',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й',
  '</w>',
  24],
 ['ф', 'и', 'н', 'и', 'к', '</w>', 24],
 ['ф', 'о', 'р', 'е', 'л', 'ь', '</w>', 24],
 ['х', 'р', 'е', 'н', '</w>', 24],
 ['к',
  'р',
  'у',
  'п',
  'а',
  '</w>',
  'п',
  'е',
  'р',
  'л',
  'о',
  'в',
  'ы',
  'й',
  '</w>',
  23],
 ['с',
  'е',
  'л',
  'ь',
  'д',
  'е',
  'р',
  'е',
  'й',
  '</w>',
  'к',
  'о',
  'р',
  'н',
  'е',
  'в',
  '</w>',
  23],
 ['с',
  'е',
  'м',
  'е',
  'ч',
  'к',
  'и',
  '</w>',
  'п',
  'о',
  'д',
  'с',
  'о',
  'л',
  'н',
  'у',
  'х',
  '</w>',
  23],
 ['с',
  'м',
  'о',
  'р',
  'о',
  'д',
  'и',
  'н',
  'а',
  '</w>',
  'ч',
  'е',
  'р',
  'н',
  'ы',
  'й',
  '</w>',
  23],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й',
  '</w>',
  23],
 ['б', 'а', 'л', 'ь', 'з', 'а', 'м', 'и', 'к', '</w>', 22],
 ['к', 'у', 'с', '-', 'к', 'у', 'с', '</w>', 22],
 ['с',
  'ы',
  'р',
  '</w>',
  'п',
  'о',
  'л',
  'у',
  'т',
  'в',
  'е',
  'р',
  'д',
  'ы',
  'й',
  '</w>',
  22],
 ['т', 'е', 'л', 'я', 'т', 'и', 'н', 'а', '</w>', 22],
 ['ц', 'у', 'к', 'к', 'и', 'н', 'я', '</w>', 22],
 ['я',
  'й',
  'ц',
  'о',
  '</w>',
  'п',
  'е',
  'р',
  'е',
  'п',
  'е',
  'л',
  'и',
  'н',
  'ы',
  'й',
  '</w>',
  22],
 ['и', 'к', 'р', 'а', '</w>', 'к', 'р', 'а', 'с', 'н', 'ы', 'й', '</w>', 21],
 ['к', 'а', 'п', 'е', 'р', 'с', '</w>', 21],
 ['ф', 'р', 'у', 'к', 'т', '</w>', 21],
 ['б', 'л', 'и', 'н', '</w>', 20],
 ['л', 'а', 'п', 'ш', 'а', '</w>', 20],
 ['м', 'а', 'с', 'к', 'а', 'р', 'п', 'о', 'н', '</w>', 20],
 ['м', 'о', 'р', 'о', 'ж', 'е', 'н', 'о', 'е', '</w>', 20],
 ['о',
  'л',
  'и',
  'в',
  'к',
  'и',
  '</w>',
  'ч',
  'е',
  'р',
  'н',

In [33]:
def get_pair_frequencies(corpus):
    pair_freq = defaultdict(int)

    for word in corpus:

        freq = word[-1]
        symbols = word[:-1]


        for i in range(len(symbols) - 1):
            pair = (symbols[i], symbols[i + 1])
            pair_freq[pair] += freq

    return pair_freq

In [34]:
pair_freq = get_pair_frequencies(corpus)
best_pair = max(pair_freq, key=pair_freq.get)
print(best_pair, pair_freq[best_pair])

('й', '</w>') 21314

In [35]:
def merge_pair(pair, corpus):
    new_corpus = []

    a, b = pair
    merged = a + b

    for word in corpus:
        freq = word[-1]
        symbols = word[:-1]

        new_symbols = []
        i = 0
        while i < len(symbols):
            if i < len(symbols) - 1 and symbols[i] == a and symbols[i + 1] == b:
                new_symbols.append(merged)
                i += 2
            else:
                new_symbols.append(symbols[i])
                i += 1

        new_corpus.append(new_symbols + [freq])

    return new_corpus

In [36]:
merge_pair(best_pair, corpus)

[['с', 'о', 'л', 'ь', '</w>', 3125],
 ['я', 'й', 'ц', 'о', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й</w>', 2342],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'п',
  'ш',
  'е',
  'н',
  'и',
  'ч',
  'н',
  'ы',
  'й</w>',
  2046],
 ['с', 'а', 'х', 'а', 'р', '</w>', 1966],
 ['л', 'у', 'к', '</w>', 'р', 'е', 'п', 'ч', 'а', 'т', 'ы', 'й</w>', 1656],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'р',
  'а',
  'с',
  'т',
  'и',
  'т',
  'е',
  'л',
  'ь',
  'н',
  'ы',
  'й</w>',
  1573],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'с',
  'л',
  'и',
  'в',
  'о',
  'ч',
  'н',
  'ы',
  'й</w>',
  1526],
 ['ч', 'е', 'с', 'н', 'о', 'к', '</w>', 1229],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'ч', 'ё', 'р', 'н', 'ы', 'й</w>', 1131],
 ['в', 'о', 'д', 'а', '</w>', 1019],
 ['м', 'о', 'л', 'о', 'к', 'о', '</w>', 955],
 ['м', 'о', 'р', 'к', 'о', 'в', 'ь', '</w>', 898],
 ['с', 'м', 'е', 'т', 'а', 'н', 'а', '</w>', 750],
 ['м', 'а', 'й', 'о', 'н', 'е', 'з', '</w>', 690],
 ['к', 'а', 'р', 'т', 'о', 'ф', 'е', 'л', 'ь', '</w>', 647],
 ['р',
  'а',
  'з',
  'р',
  'ы',
  'х',
  'л',
  'и',
  'т',
  'е',
  'л',
  'ь',
  '</w>',
  'т',
  'е',
  'с',
  'т',
  '</w>',
  631],
 ['с', 'ы', 'р', '</w>', 'т', 'в', 'ё', 'р', 'д', 'ы', 'й</w>', 611],
 ['п', 'о', 'м', 'и', 'д', 'о', 'р', '</w>', 604],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'о',
  'л',
  'и',
  'в',
  'к',
  'о',
  'в',
  'ы',
  'й</w>',
  532],
 ['з', 'е', 'л', 'е', 'н', 'ь', '</w>', 530],
 ['с', 'л', 'и', 'в', 'к', 'а', '</w>', 490],
 ['с', 'п', 'е', 'ц', 'и', 'я', '</w>', 478],
 ['с', 'о', 'е', 'в', 'ы', 'й</w>', 'с', 'о', 'у', 'с', 'ы', 'й</w>', 468],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'б',
  'о',
  'л',
  'г',
  'а',
  'р',
  'с',
  'к',
  'и',
  'й</w>',
  419],
 ['д', 'р', 'о', 'ж', 'ж', 'и', '</w>', 385],
 ['с',
  'а',
  'х',
  'а',
  'р',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'у',
  'д',
  'р',
  'ы',
  'й</w>',
  371],
 ['п', 'е', 'т', 'р', 'у', 'ш', 'к', 'а', '</w>', 369],
 ['с', 'о', 'к', '</w>', 'л', 'и', 'м', 'о', 'н', 'н', 'ы', 'й</w>', 363],
 ['т', 'в', 'о', 'р', 'о', 'г', '</w>', 356],
 ['м', 'ё', 'д', '</w>', 350],
 ['у', 'к', 'с', 'у', 'с', '</w>', 345],
 ['у', 'к', 'р', 'о', 'п', '</w>', 335],
 ['я', 'б', 'л', 'о', 'к', 'о', '</w>', 332],
 ['с', 'о', 'д', 'а', '</w>', 316],
 ['р', 'и', 'с', '</w>', 307],
 ['в',
  'а',
  'н',
  'и',
  'л',
  'ь',
  'н',
  'ы',
  'й</w>',
  'с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  305],
 ['о', 'г', 'у', 'р', 'е', 'ц', '</w>', 295],
 ['в', 'а', 'н', 'и', 'л', 'и', 'н', '</w>', 294],
 ['к', 'о', 'р', 'и', 'ц', 'а', '</w>', 283],
 ['о', 'р', 'е', 'х', 'и', '</w>', 'г', 'р', 'е', 'ц', 'к', 'и', 'й</w>', 276],
 ['ж', 'е', 'л', 'т', 'о', 'к', '</w>', 'я', 'и', 'ч', 'н', 'ы', 'й</w>', 272],
 ['л', 'и', 'м', 'о', 'н', '</w>', 271],
 ['к',
  'а',
  'к',
  'а',
  'о',
  '-',
  'п',
  'о',
  'р',
  'о',
  'ш',
  'о',
  'к',
  '</w>',
  270],
 ['л', 'у', 'к', '</w>', 'з', 'е', 'л', 'ё', 'н', 'ы', 'й</w>', 256],
 ['ш', 'а', 'м', 'п', 'и', 'н', 'ь', 'о', 'н', '</w>', 240],
 ['п', 'р', 'и', 'п', 'р', 'а', 'в', 'а', '</w>', 237],
 ['г', 'о', 'р', 'ч', 'и', 'ц', 'а', '</w>', 234],
 ['ф', 'а', 'р', 'ш', '</w>', 'м', 'я', 'с', 'н', 'о', 'й</w>', 228],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'п',
  'о',
  'д',
  'с',
  'о',
  'л',
  'н',
  'е',
  'ч',
  'н',
  'ы',
  'й</w>',
  225],
 ['л', 'и', 'с', 'т', '</w>', 'л', 'а', 'в', 'р', 'о', 'в', 'ы', 'й</w>', 215],
 ['г', 'р', 'и', 'б', '</w>', 207],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'а',
  'с',
  'т',
  'а',
  '</w>',
  201],
 ['к', 'а', 'б', 'а', 'ч', 'о', 'к', '</w>', 194],
 ['ф', 'и', 'л', 'е', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й</w>', 192],
 ['и', 'з', 'ю', 'м', '</w>', 184],
 ['с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  'к',
  'о',
  'р',
  'и',
  'ч',
  'н',
  'е',
  'в',
  'ы',
  'й</w>',
  183],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'д',
  'у',
  'ш',
  'и',
  'с',
  'т',
  'ы',
  'й</w>',
  175],
 ['ш',
  'о',
  'к',
  'о',
  'л',
  'а',
  'д',
  '</w>',
  'т',
  'ё',
  'м',
  'н',
  'ы',
  'й</w>',
  175],
 ['и', 'м', 'б', 'и', 'р', 'ь', '</w>', 171],
 ['к', 'у', 'н', 'ж', 'у', 'т', '</w>', 169],
 ['б', 'а', 'к', 'л', 'а', 'ж', 'а', 'н', '</w>', 163],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'ы',
  'й</w>',
  'ж',
  'г',
  'у',
  'ч',
  'и',
  'й</w>',
  162],
 ['ж', 'е', 'л', 'а', 'т', 'и', 'н', 'а', '</w>', 161],
 ['п',
  'а',
  'п',
  'р',
  'и',
  'к',
  'а',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й</w>',
  161],
 ['б', 'у', 'л', 'ь', 'о', 'н', '</w>', 160],
 ['с', 'в', 'и', 'н', 'и', 'н', 'а', '</w>', 158],
 ['к', 'е', 'ф', 'и', 'р', '</w>', 156],
 ['к', 'р', 'у', 'п', 'а', '</w>', 'м', 'а', 'т', 'ь', '</w>', 156],
 ['м', 'а', 'р', 'г', 'а', 'р', 'и', 'н', '</w>', 156],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'б',
  'е',
  'л',
  'о',
  'к',
  'о',
  'ч',
  'а',
  'т',
  'ь',
  '</w>',
  155],
 ['г',
  'р',
  'у',
  'д',
  'к',
  'а',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й</w>',
  153],
 ['й', 'о', 'г', 'у', 'р', 'т', '</w>', 149],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'ч', 'и', 'л', 'и', '</w>', 145],
 ['б', 'е', 'л', 'о', 'к', '</w>', 'я', 'и', 'ч', 'н', 'ы', 'й</w>', 144],
 ['м',
  'о',
  'л',
  'о',
  'к',
  'о',
  '</w>',
  'с',
  'г',
  'у',
  'щ',
  'е',
  'н',
  'н',
  'ы',
  'й</w>',
  144],
 ['л', 'и', 'с', 'т', 'ь', 'я', '</w>', 'с', 'а', 'л', 'а', 'т', '</w>', 139],
 ['б', 'а', 'з', 'и', 'л', 'и', 'к', '</w>', 134],
 ['к', 'р', 'а', 'х', 'м', 'а', 'л', '</w>', 133],
 ['с',
  'у',
  'х',
  'а',
  'р',
  'и',
  '</w>',
  'п',
  'а',
  'н',
  'и',
  'р',
  'о',
  'в',
  'о',
  'ч',
  'н',
  'ы',
  'й</w>',
  133],
 ['б', 'а', 'н', 'а', 'н', '</w>', 132],
 ['т', 'ы', 'к', 'в', 'а', '</w>', 132],
 ['м', 'и', 'н', 'д', 'а', 'л', 'ь', '</w>', 131],
 ['к', 'у', 'к', 'у', 'р', 'у', 'з', 'а', '</w>', 125],
 ['с', 'в', 'ё', 'к', 'л', 'а', '</w>', 118],
 ['ц', 'е', 'д', 'р', 'а', '</w>', 'л', 'и', 'м', 'о', 'н', '</w>', 118],
 ['а', 'п', 'е', 'л', 'ь', 'с', 'и', 'н', '</w>', 115],
 ['к', 'у', 'р', 'и', 'ц', 'а', '</w>', 112],
 ['ф', 'а', 'с', 'о', 'л', 'ь', '</w>', 112],
 ['к', 'о', 'р', 'и', 'а', 'н', 'д', 'р', '</w>', 110],
 ['л', 'у', 'к', '</w>', 'к', 'р', 'а', 'с', 'н', 'ы', 'й</w>', 110],
 ['к', 'и', 'н', 'з', 'а', '</w>', 108],
 ['х', 'л', 'е', 'б', '</w>', 108],
 ['ш',
  'о',
  'к',
  'о',
  'л',
  'а',
  'д',
  '</w>',
  'м',
  'о',
  'л',
  'о',
  'ч',
  'н',
  'ы',
  'й</w>',
  108],
 ['г',
  'о',
  'р',
  'о',
  'ш',
  'е',
  'к',
  '</w>',
  'з',
  'е',
  'л',
  'ё',
  'н',
  'ы',
  'й</w>',
  105],
 ['к', 'р', 'е', 'в', 'е', 'т', 'к', 'а', '</w>', 104],
 ['о',
  'р',
  'е',
  'х',
  '</w>',
  'м',
  'у',
  'с',
  'к',
  'а',
  'т',
  'н',
  'ы',
  'й</w>',
  104],
 ['в', 'и', 'ш', 'н', 'я', '</w>', 101],
 ['м', 'я', 'с', 'о', '</w>', 101],
 ['р', 'ы', 'б', 'а', '</w>', 101],
 ['с', 'о', 'у', 'с', '</w>', 98],
 ['х',
  'л',
  'о',
  'п',
  'ь',
  'я',
  '</w>',
  'о',
  'в',
  'с',
  'я',
  'н',
  'о',
  'й</w>',
  97],
 ['г', 'о', 'в', 'я', 'д', 'и', 'н', 'а', '</w>', 96],
 ['к', 'е', 'т', 'ч', 'у', 'п', '</w>', 94],
 ['с',
  'т',
  'р',
  'у',
  'ж',
  'к',
  'а',
  '</w>',
  'к',
  'о',
  'к',
  'о',
  'с',
  'о',
  'в',
  'ы',
  'й</w>',
  93],
 ['с',
  'ы',
  'р',
  '</w>',
  'г',
  'о',
  'л',
  'л',
  'а',
  'н',
  'д',
  'с',
  'к',
  'и',
  'й</w>',
  93],
 ['п',
  'о',
  'м',
  'и',
  'д',
  'о',
  'р',
  'ы',
  '</w>',
  'ч',
  'е',
  'р',
  'р',
  'и',
  '</w>',
  90],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'у',
  'к',
  'у',
  'р',
  'у',
  'з',
  'н',
  'ы',
  'й</w>',
  86],
 ['к', 'л', 'у', 'б', 'н', 'и', 'к', 'а', '</w>', 84],
 ['о', 'р', 'е', 'х', '</w>', 84],
 ['м', 'я', 'т', 'ы', 'й</w>', 83],
 ['с',
  'е',
  'л',
  'ь',
  'д',
  'е',
  'р',
  'е',
  'й</w>',
  'ч',
  'е',
  'р',
  'е',
  'ш',
  'к',
  'о',
  'в',
  'ы',
  'й</w>',
  82],
 ['к', 'о', 'л', 'б', 'а', 'с', 'а', '</w>', 80],
 ['м', 'а', 'к', '</w>', 80],
 ['п', 'е', 'ч', 'е', 'н', 'и', 'е', '</w>', 80],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'п', 'е', 'р', 'е', 'ц', '</w>', 80],
 ['в', 'е', 'т', 'ч', 'и', 'н', 'а', '</w>', 79],
 ['в',
  'и',
  'н',
  'о',
  '</w>',
  'б',
  'е',
  'л',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й</w>',
  79],
 ['ч', 'е', 'р', 'н', 'о', 'с', 'л', 'и', 'в', '</w>', 79],
 ['г', 'в', 'о', 'з', 'д', 'и', 'к', '</w>', 78],
 ['б', 'е', 'к', 'о', 'н', '</w>', 76],
 ['к',
  'р',
  'а',
  'б',
  'о',
  'в',
  'ы',
  'е',
  '</w>',
  'п',
  'а',
  'л',
  'о',
  'ч',
  'к',
  'а',
  '</w>',
  76],
 ['т', 'и', 'м', 'ь', 'я', 'н', '</w>', 73],
 ['с',
  'а',
  'х',
  'а',
  'р',
  '</w>',
  'т',
  'р',
  'о',
  'с',
  'т',
  'н',
  'и',
  'к',
  'о',
  'в',
  'ы',
  'й</w>',
  72],
 ['р', 'о', 'з', 'м', 'а', 'р', 'и', 'н', '</w>', 68],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'а',
  'р',
  'т',
  'о',
  'ф',
  'е',
  'л',
  'ь',
  'н',
  'ы',
  'й</w>',
  67],
 ['к',
  'р',
  'у',
  'п',
  'а',
  '</w>',
  'г',
  'р',
  'е',
  'ч',
  'н',
  'е',
  'в',
  'ы',
  'й</w>',
  67],
 ['л', 'у', 'к', '-', 'п', 'о', 'р', 'е', 'й</w>', 66],
 ['с', 'ы', 'р', '</w>', 'п', 'л', 'а', 'в', 'л', 'е', 'н', 'ы', 'й</w>', 66],
 ['м',
  'а',
  'к',
  'а',
  'р',
  'о',
  'н',
  'н',
  'ы',
  'е',
  '</w>',
  'и',
  'з',
  'д',
  'е',
  'л',
  'и',
  'е',
  '</w>',
  65],
 ['м', 'а', 'с', 'л', 'и', 'н', 'а', '</w>', 64],
 ['а', 'н', 'а', 'н', 'а', 'с', '</w>', 63],
 ['к', 'о', 'н', 'ь', 'я', 'к', '</w>', 63],
 ['ш', 'п', 'и', 'н', 'а', 'т', '</w>', 62],
 ['с', 'ы', 'р', '</w>', 'т', 'в', 'о', 'р', 'о', 'ж', 'н', 'ы', 'й</w>', 59],
 ['т', 'е', 'с', 'т', 'о', '</w>', 'с', 'л', 'о', 'ё', 'н', 'ы', 'й</w>', 59],
 ['в', 'а', 'р', 'е', 'н', 'и', 'е', '</w>', 58],
 ['к', 'а', 'р', 'р', 'и', '</w>', 58],
 ['к', 'у', 'р', 'к', 'у', 'м', 'а', '</w>', 58],
 ['к', 'у', 'р', 'а', 'г', 'а', '</w>', 56],
 ['о', 'р', 'е', 'г', 'а', 'н', 'о', '</w>', 55],
 ['п', 'а', 'р', 'м', 'е', 'з', 'а', 'н', '</w>', 55],
 ['т', 'м', 'и', 'н', '</w>', 55],
 ['ш', 'о', 'к', 'о', 'л', 'а', 'д', '</w>', 'б', 'е', 'л', 'ы', 'й</w>', 55],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'ц',
  'в',
  'е',
  'т',
  'н',
  'ы',
  'й</w>',
  54],
 ['ц',
  'е',
  'д',
  'р',
  'а',
  '</w>',
  'а',
  'п',
  'е',
  'л',
  'ь',
  'с',
  'и',
  'н',
  'а',
  '</w>',
  54],
 ['г', 'р', 'у', 'ш', 'а', '</w>', 53],
 ['л', 'у', 'к', '</w>', 'б', 'е', 'л', 'ы', 'й</w>', 53],
 ['о',
  'л',
  'и',
  'в',
  'к',
  'и',
  '</w>',
  'з',
  'е',
  'л',
  'ё',
  'н',
  'ы',
  'й</w>',
  53],
 ['с', 'а', 'л', 'о', '</w>', 53],
 ['с',
  'о',
  'д',
  'а',
  '</w>',
  'г',
  'а',
  'ш',
  'е',
  'н',
  'а',
  'я',
  '</w>',
  'у',
  'к',
  'с',
  'у',
  'с',
  '</w>',
  53],
 ['с',
  'о',
  'к',
  '</w>',
  'а',
  'п',
  'е',
  'л',
  'ь',
  'с',
  'и',
  'н',
  'о',
  'в',
  'ы',
  'й</w>',
  53],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а',
  '</w>',
  'п',
  'е',
  'к',
  'и',
  'н',
  'с',
  'к',
  'и',
  'й</w>',
  52],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'с', 'л', 'а', 'д', 'к', 'и', 'й</w>', 52],
 ['д', 'ж', 'е', 'м', 'а', '</w>', 51],
 ['к', 'л', 'ю', 'к', 'в', 'а', '</w>', 51],
 ['с', 'ы', 'р', '</w>', 'с', 'л', 'и', 'в', 'о', 'ч', 'н', 'ы', 'й</w>', 51],
 ['к', 'а', 'л', 'ь', 'м', 'а', 'р', '</w>', 50],
 ['с', 'ы', 'р', '</w>', 'м', 'я', 'г', 'к', 'и', 'й</w>', 50],
 ['о',
  'г',
  'у',
  'р',
  'е',
  'ц',
  '</w>',
  'м',
  'а',
  'р',
  'и',
  'н',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  49],
 ['п',
  'е',
  'ч',
  'е',
  'н',
  'ь',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й</w>',
  48],
 ['с', 'е', 'л', 'ь', 'д', 'ь', '</w>', 48],
 ['ф', 'и', 'л', 'е', '</w>', 'р', 'ы', 'б', 'н', 'ы', 'й</w>', 47],
 ['а', 'в', 'о', 'к', 'а', 'д', 'о', '</w>', 46],
 ['о',
  'р',
  'е',
  'х',
  'и',
  '</w>',
  'к',
  'е',
  'д',
  'р',
  'о',
  'в',
  'ы',
  'й</w>',
  46],
 ['п',
  'е',
  'р',
  'е',
  'ц',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'ы',
  'й</w>',
  46],
 ['л', 'а', 'в', 'а', 'ш', '</w>', 43],
 ['м', 'о', 'ц', 'а', 'р', 'е', 'л', 'л', 'а', '</w>', 42],
 ['п', 'е', 'р', 'е', 'ц', '</w>', 'б', 'е', 'л', 'ы', 'й</w>', 42],
 ['и', 'н', 'д', 'е', 'й', 'к', 'а', '</w>', 41],
 ['л', 'и', 'к', 'ё', 'р', '</w>', 41],
 ['о',
  'к',
  'о',
  'р',
  'о',
  'ч',
  'о',
  'к',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й</w>',
  41],
 ['б', 'а', 'т', 'о', 'н', '</w>', 40],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'р',
  'а',
  'с',
  'т',
  'в',
  'о',
  'р',
  'и',
  'м',
  'ы',
  'й</w>',
  40],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'ц',
  'е',
  'л',
  'ь',
  'н',
  'о',
  'з',
  'е',
  'р',
  'н',
  'о',
  'в',
  'ы',
  'й</w>',
  40],
 ['б', 'р', 'о', 'к', 'к', 'о', 'л', 'и', '</w>', 39],
 ['к', 'а', 'р', 'д', 'а', 'м', 'о', 'н', '</w>', 39],
 ['к',
  'и',
  'с',
  'л',
  'о',
  'т',
  'а',
  '</w>',
  'л',
  'и',
  'м',
  'о',
  'н',
  'н',
  'ы',
  'й</w>',
  39],
 ['м', 'у', 'к', 'а', '</w>', 'р', 'ж', 'а', 'н', 'о', 'й</w>', 39],
 ['м', 'а', 'л', 'и', 'н', 'а', '</w>', 38],
 ['р', 'е', 'д', 'и', 'с', '</w>', 38],
 ['с', 'о', 'с', 'и', 'с', 'к', 'а', '</w>', 38],
 ['ф',
  'а',
  'с',
  'о',
  'л',
  'ь',
  '</w>',
  'к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'и',
  'р',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  38],
 ['ч', 'е', 'ч', 'е', 'в', 'и', 'ц', 'а', '</w>', 38],
 ['а', 'р', 'а', 'х', 'и', 'с', '</w>', 37],
 ['в', 'о', 'д', 'к', 'а', '</w>', 37],
 ['я', 'г', 'о', 'д', 'а', '</w>', 37],
 ['б', 'р', 'ы', 'н', 'з', 'а', '</w>', 36],
 ['п',
  'о',
  'р',
  'о',
  'ш',
  'о',
  'к',
  '</w>',
  'ч',
  'е',
  'с',
  'н',
  'о',
  'ч',
  'н',
  'ы',
  'й</w>',
  36],
 ['к', 'и', 'в', 'и', '</w>', 35],
 ['с', 'о', 'к', '</w>', 35],
 ['с',
  'ы',
  'р',
  'о',
  'к',
  '</w>',
  'п',
  'л',
  'а',
  'в',
  'л',
  'ё',
  'н',
  'ы',
  'й</w>',
  35],
 ['ф', 'а', 'р', 'ш', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й</w>', 35],
 ['в', 'а', 'н', 'и', 'л', 'ь', '</w>', 34],
 ['с', 'у', 'х', 'а', 'р', 'и', 'к', '</w>', 34],
 ['б', 'е', 'д', 'р', 'о', '</w>', 'к', 'у', 'р', 'и', 'н', 'ы', 'й</w>', 33],
 ['з', 'и', 'р', 'а', '</w>', 33],
 ['п', 'е', 'р', 'с', 'и', 'к', '</w>', 33],
 ['ф',
  'а',
  'с',
  'о',
  'л',
  'ь',
  '</w>',
  'с',
  'т',
  'р',
  'у',
  'ч',
  'к',
  'о',
  'в',
  'ы',
  'й</w>',
  33],
 ['х', 'м', 'е', 'л', 'ь', '-', 'с', 'у', 'н', 'е', 'л', 'ь', '</w>', 33],
 ['ц', 'у', 'к', 'а', 'т', '</w>', 33],
 ['а', 'б', 'р', 'и', 'к', 'о', 'с', '</w>', 32],
 ['к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'ы',
  '</w>',
  'р',
  'ы',
  'б',
  'н',
  'ы',
  'й</w>',
  32],
 ['м',
  'у',
  'к',
  'а',
  '</w>',
  'к',
  'у',
  'к',
  'у',
  'р',
  'у',
  'з',
  'н',
  'ы',
  'й</w>',
  32],
 ['н', 'у', 'т', '</w>', 32],
 ['с', 'л', 'и', 'в', 'а', '</w>', 32],
 ['в', 'и', 'н', 'о', 'г', 'р', 'а', 'д', '</w>', 31],
 ['л', 'о', 'с', 'о', 'с', 'ь', '</w>', 31],
 ['б', 'а', 'р', 'а', 'н', 'и', 'н', 'а', '</w>', 30],
 ['г',
  'о',
  'л',
  'е',
  'н',
  'ь',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й</w>',
  30],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'н',
  'а',
  'т',
  'у',
  'р',
  'а',
  'л',
  'ь',
  'н',
  'ы',
  'й</w>',
  30],
 ['о',
  'г',
  'у',
  'р',
  'е',
  'ц',
  '</w>',
  'с',
  'о',
  'л',
  'ё',
  'н',
  'ы',
  'й</w>',
  30],
 ['т', 'у', 'н', 'е', 'ц', '</w>', 30],
 ['ф', 'у', 'н', 'д', 'у', 'к', '</w>', 30],
 ['г', 'р', 'у', 'д', 'и', 'н', 'к', 'а', '</w>', 29],
 ['п',
  'е',
  'ч',
  'е',
  'н',
  'ь',
  '</w>',
  'г',
  'о',
  'в',
  'я',
  'ж',
  'и',
  'й</w>',
  29],
 ['р', 'о', 'м', '</w>', 29],
 ['с', 'ё', 'м', 'г', 'а', '</w>', 29],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'ы',
  '</w>',
  'в',
  '</w>',
  'с',
  'о',
  'б',
  'с',
  'т',
  'в',
  'е',
  'н',
  'н',
  'о',
  'м',
  '</w>',
  'с',
  'о',
  'к',
  'а',
  '</w>',
  29],
 ['в',
  'и',
  'н',
  'о',
  '</w>',
  'к',
  'р',
  'а',
  'с',
  'н',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й</w>',
  28],
 ['з', 'а', 'к', 'в', 'а', 'с', 'к', 'а', '</w>', 28],
 ['м', 'а', 'н', 'д', 'а', 'р', 'и', 'н', '</w>', 28],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'к',
  'у',
  'н',
  'ж',
  'у',
  'т',
  'н',
  'ы',
  'й</w>',
  28],
 ['ж', 'е', 'л', 'е', '</w>', 27],
 ['к',
  'р',
  'а',
  'с',
  'и',
  'т',
  'е',
  'л',
  'ь',
  '</w>',
  'п',
  'и',
  'щ',
  'е',
  'в',
  '</w>',
  27],
 ['м',
  'а',
  'с',
  'л',
  'о',
  '</w>',
  'т',
  'о',
  'п',
  'л',
  'ё',
  'н',
  'ы',
  'й</w>',
  27],
 ['п',
  'о',
  'с',
  'ы',
  'п',
  'к',
  'а',
  '</w>',
  'к',
  'о',
  'н',
  'д',
  'и',
  'т',
  'е',
  'р',
  'с',
  'к',
  'и',
  'й</w>',
  27],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'с', 'п', 'е', 'ц', 'и', 'я', '</w>', 27],
 ['с', 'о', 'к', '</w>', 'т', 'о', 'м', 'а', 'т', 'н', 'ы', 'й</w>', 26],
 ['ш', 'а', 'ф', 'р', 'а', 'н', '</w>', 26],
 ['к',
  'р',
  'ы',
  'л',
  'ь',
  'я',
  '</w>',
  'к',
  'у',
  'р',
  'и',
  'н',
  'ы',
  'й</w>',
  25],
 ['п', 'ш', 'е', 'н', 'о', '</w>', 25],
 ['с', 'ы', 'в', 'о', 'р', 'о', 'т', 'к', 'а', '</w>', 25],
 ['ф', 'е', 'т', '</w>', 25],
 ['б', 'р', 'у', 'с', 'н', 'и', 'к', 'а', '</w>', 24],
 ['л', 'а', 'й', 'м', '</w>', 24],
 ['о', 'в', 'о', 'щ', '</w>', 24],
 ['с', 'о', 'у', 'с', '-', 'м', 'а', 'р', 'и', 'н', 'а', 'д', '</w>', 24],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'с',
  'л',
  'о',
  'е',
  'н',
  'о',
  'е',
  '</w>',
  'б',
  'е',
  'з',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  24],
 ['ф', 'и', 'н', 'и', 'к', '</w>', 24],
 ['ф', 'о', 'р', 'е', 'л', 'ь', '</w>', 24],
 ['х', 'р', 'е', 'н', '</w>', 24],
 ['к',
  'р',
  'у',
  'п',
  'а',
  '</w>',
  'п',
  'е',
  'р',
  'л',
  'о',
  'в',
  'ы',
  'й</w>',
  23],
 ['с',
  'е',
  'л',
  'ь',
  'д',
  'е',
  'р',
  'е',
  'й</w>',
  'к',
  'о',
  'р',
  'н',
  'е',
  'в',
  '</w>',
  23],
 ['с',
  'е',
  'м',
  'е',
  'ч',
  'к',
  'и',
  '</w>',
  'п',
  'о',
  'д',
  'с',
  'о',
  'л',
  'н',
  'у',
  'х',
  '</w>',
  23],
 ['с',
  'м',
  'о',
  'р',
  'о',
  'д',
  'и',
  'н',
  'а',
  '</w>',
  'ч',
  'е',
  'р',
  'н',
  'ы',
  'й</w>',
  23],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  23],
 ['б', 'а', 'л', 'ь', 'з', 'а', 'м', 'и', 'к', '</w>', 22],
 ['к', 'у', 'с', '-', 'к', 'у', 'с', '</w>', 22],
 ['с',
  'ы',
  'р',
  '</w>',
  'п',
  'о',
  'л',
  'у',
  'т',
  'в',
  'е',
  'р',
  'д',
  'ы',
  'й</w>',
  22],
 ['т', 'е', 'л', 'я', 'т', 'и', 'н', 'а', '</w>', 22],
 ['ц', 'у', 'к', 'к', 'и', 'н', 'я', '</w>', 22],
 ['я',
  'й',
  'ц',
  'о',
  '</w>',
  'п',
  'е',
  'р',
  'е',
  'п',
  'е',
  'л',
  'и',
  'н',
  'ы',
  'й</w>',
  22],
 ['и', 'к', 'р', 'а', '</w>', 'к', 'р', 'а', 'с', 'н', 'ы', 'й</w>', 21],
 ['к', 'а', 'п', 'е', 'р', 'с', '</w>', 21],
 ['ф', 'р', 'у', 'к', 'т', '</w>', 21],
 ['б', 'л', 'и', 'н', '</w>', 20],
 ['л', 'а', 'п', 'ш', 'а', '</w>', 20],
 ['м', 'а', 'с', 'к', 'а', 'р', 'п', 'о', 'н', '</w>', 20],
 ['м', 'о', 'р', 'о', 'ж', 'е', 'н', 'о', 'е', '</w>', 20],
 ['о', 'л', 'и', 'в', 'к', 'и', '</w>', 'ч', 'е', 'р', 'н', 'ы', 'й</w>', 20],
 ['о', 'т', 'р', 'у', 'б', 'и', '</w>', 20],
 ['т',
  'е',
  'с',
  'т',
  'о',
  '</w>',
  'с',
  'л',
  'о',
  'е',
  'н',
  'о',
  'е',
  '</w>',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  20],
 ['ч', 'а', 'й</w>', 'ч', 'ё', 'р', 'н', 'ы', 'й</w>', 20],
 ['г', 'о', 'р', 'б', 'у', 'ш', 'а', '</w>', 19],
 ['р', 'у', 'к', 'к', 'о', 'л', 'а', '</w>', 19],
 ['с', 'е', 'м', 'е', 'н', 'а', '</w>', 'л', 'ь', 'н', 'ы', 'й</w>', 19],
 ['с', 'к', 'у', 'м', 'б', 'р', 'и', 'я', '</w>', 19],
 ['ч', 'е', 'р', 'н', 'и', 'к', 'а', '</w>', 19],
 ['г', 'р', 'а', 'н', 'а', 'т', '</w>', 18],
 ['к',
  'у',
  'б',
  'и',
  'к',
  '</w>',
  'б',
  'у',
  'л',
  'ь',
  'о',
  'н',
  'н',
  'ы',
  'й</w>',
  18],
 ['л', 'у', 'к', '-', 'ш', 'а', 'л', 'о', 'т', '</w>', 18],

In [37]:
def bpe(n, corpus):
    for j in range(n):
        pair_freq = get_pair_frequencies(corpus)
        best_pair = max(pair_freq, key=pair_freq.get)

        corpus = merge_pair(best_pair, corpus)
    return corpus

In [38]:

bpe(22, corpus)

[['со', 'ль</w>', 3125],
 ['я', 'й', 'ц', 'о</w>', 'ку', 'ри', 'ный</w>', 2342],
 ['м', 'ук', 'а</w>', 'п', 'ш', 'е', 'ни', 'чный</w>', 2046],
 ['с', 'а', 'х', 'ар', '</w>', 1966],
 ['л', 'ук', '</w>', 'ре', 'п', 'ч', 'а', 'т', 'ый</w>', 1656],
 ['масло</w>', 'р', 'ас', 'т', 'и', 'т', 'е', 'ль', 'ный</w>', 1573],
 ['масло</w>', 'с', 'ли', 'в', 'о', 'чный</w>', 1526],
 ['ч', 'е', 'с', 'н', 'ок', '</w>', 1229],
 ['пе', 'ре', 'ц', '</w>', 'ч', 'ё', 'р', 'ный</w>', 1131],
 ['в', 'о', 'д', 'а</w>', 1019],
 ['м', 'о', 'л', 'ок', 'о</w>', 955],
 ['м', 'о', 'р', 'к', 'о', 'в', 'ь', '</w>', 898],
 ['с', 'м', 'е', 'т', 'а', 'н', 'а</w>', 750],
 ['м', 'а', 'й', 'о', 'н', 'е', 'з', '</w>', 690],
 ['к', 'ар', 'т', 'о', 'ф', 'е', 'ль</w>', 647],
 ['р',
  'а',
  'з',
  'р',
  'ы',
  'х',
  'ли',
  'т',
  'е',
  'ль</w>',
  'т',
  'е',
  'с',
  'т',
  '</w>',
  631],
 ['с', 'ы', 'р', '</w>', 'т', 'в', 'ё', 'р', 'д', 'ый</w>', 611],
 ['п', 'о', 'м', 'и', 'д', 'о', 'р', '</w>', 604],
 ['масло</w>', 'о', 'ли', 'в', 'к', 'о', 'в', 'ый</w>', 532],
 ['з', 'е', 'л', 'е', 'н', 'ь', '</w>', 530],
 ['с', 'ли', 'в', 'к', 'а</w>', 490],
 ['с', 'пе', 'ц', 'и', 'я', '</w>', 478],
 ['со', 'е', 'в', 'ый</w>', 'со', 'у', 'с', 'ый</w>', 468],
 ['пе',
  'ре',
  'ц',
  '</w>',
  'б',
  'о',
  'л',
  'г',
  'ар',
  'с',
  'к',
  'и',
  'й</w>',
  419],
 ['д', 'р', 'о', 'ж', 'ж', 'и', '</w>', 385],
 ['с',
  'а',
  'х',
  'ар',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'у',
  'д',
  'р',
  'ый</w>',
  371],
 ['пе', 'т', 'р', 'у', 'ш', 'к', 'а</w>', 369],
 ['со', 'к', '</w>', 'ли', 'м', 'о', 'н', 'ный</w>', 363],
 ['т', 'в', 'о', 'р', 'о', 'г', '</w>', 356],
 ['м', 'ё', 'д', '</w>', 350],
 ['ук', 'с', 'у', 'с', '</w>', 345],
 ['ук', 'р', 'о', 'п', '</w>', 335],
 ['я', 'б', 'л', 'ок', 'о</w>', 332],
 ['со', 'д', 'а</w>', 316],
 ['ри', 'с', '</w>', 307],
 ['в', 'а', 'ни', 'ль', 'ный</w>', 'с', 'а', 'х', 'ар', '</w>', 305],
 ['о', 'г', 'у', 'ре', 'ц', '</w>', 295],
 ['в', 'а', 'ни', 'ли', 'н', '</w>', 294],
 ['к', 'о', 'ри', 'ц', 'а</w>', 283],
 ['о', 'ре', 'х', 'и', '</w>', 'г', 'ре', 'ц', 'к', 'и', 'й</w>', 276],
 ['ж', 'е', 'л', 'т', 'ок', '</w>', 'я', 'и', 'чный</w>', 272],
 ['ли', 'м', 'о', 'н', '</w>', 271],
 ['к', 'а', 'к', 'а', 'о', '-', 'п', 'о', 'р', 'о', 'ш', 'ок', '</w>', 270],
 ['л', 'ук', '</w>', 'з', 'е', 'л', 'ё', 'ный</w>', 256],
 ['ш', 'а', 'м', 'п', 'и', 'н', 'ь', 'о', 'н', '</w>', 240],
 ['п', 'ри', 'п', 'р', 'а', 'в', 'а</w>', 237],
 ['г', 'о', 'р', 'ч', 'и', 'ц', 'а</w>', 234],
 ['ф', 'ар', 'ш', '</w>', 'м', 'я', 'с', 'н', 'о', 'й</w>', 228],
 ['масло</w>', 'п', 'о', 'д', 'со', 'л', 'н', 'е', 'чный</w>', 225],
 ['ли', 'с', 'т', '</w>', 'л', 'а', 'в', 'р', 'о', 'в', 'ый</w>', 215],
 ['г', 'ри', 'б', '</w>', 207],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'н',
  'а',
  'я',
  '</w>',
  'п',
  'ас',
  'т',
  'а</w>',
  201],
 ['к', 'а', 'б', 'а', 'ч', 'ок', '</w>', 194],
 ['ф', 'и', 'л', 'е', '</w>', 'ку', 'ри', 'ный</w>', 192],
 ['и', 'з', 'ю', 'м', '</w>', 184],
 ['с',
  'а',
  'х',
  'ар',
  '</w>',
  'к',
  'о',
  'ри',
  'ч',
  'н',
  'е',
  'в',
  'ый</w>',
  183],
 ['пе', 'ре', 'ц', '</w>', 'д', 'у', 'ш', 'и', 'с', 'т', 'ый</w>', 175],
 ['ш', 'ок', 'о', 'л', 'а', 'д', '</w>', 'т', 'ё', 'м', 'ный</w>', 175],
 ['и', 'м', 'б', 'и', 'р', 'ь', '</w>', 171],
 ['ку', 'н', 'ж', 'у', 'т', '</w>', 169],
 ['б', 'а', 'к', 'л', 'а', 'ж', 'а', 'н', '</w>', 163],
 ['пе',
  'ре',
  'ц',
  '</w>',
  'к',
  'р',
  'ас',
  'ный</w>',
  'ж',
  'г',
  'у',
  'ч',
  'и',
  'й</w>',
  162],
 ['ж', 'е', 'л', 'а', 'т', 'и', 'н', 'а</w>', 161],
 ['п',
  'а',
  'п',
  'ри',
  'к',
  'а</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й</w>',
  161],
 ['б', 'у', 'ль', 'о', 'н', '</w>', 160],
 ['с', 'в', 'и', 'ни', 'н', 'а</w>', 158],
 ['к', 'е', 'ф', 'и', 'р', '</w>', 156],
 ['к', 'р', 'у', 'п', 'а</w>', 'м', 'а', 'т', 'ь', '</w>', 156],
 ['м', 'ар', 'г', 'ар', 'и', 'н', '</w>', 156],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а</w>',
  'б',
  'е',
  'л',
  'ок',
  'о',
  'ч',
  'а',
  'т',
  'ь',
  '</w>',
  155],
 ['г', 'р', 'у', 'д', 'к', 'а</w>', 'ку', 'ри', 'ный</w>', 153],
 ['й', 'о', 'г', 'у', 'р', 'т', '</w>', 149],
 ['пе', 'ре', 'ц', '</w>', 'ч', 'и', 'ли', '</w>', 145],
 ['б', 'е', 'л', 'ок', '</w>', 'я', 'и', 'чный</w>', 144],
 ['м', 'о', 'л', 'ок', 'о</w>', 'с', 'г', 'у', 'щ', 'е', 'н', 'ный</w>', 144],
 ['ли', 'с', 'т', 'ь', 'я', '</w>', 'с', 'а', 'л', 'а', 'т', '</w>', 139],
 ['б', 'а', 'з', 'и', 'ли', 'к', '</w>', 134],
 ['к', 'р', 'а', 'х', 'м', 'а', 'л', '</w>', 133],
 ['с',
  'у',
  'х',
  'ар',
  'и',
  '</w>',
  'п',
  'а',
  'ни',
  'р',
  'о',
  'в',
  'о',
  'чный</w>',
  133],
 ['б', 'а', 'н', 'а', 'н', '</w>', 132],
 ['т', 'ы', 'к', 'в', 'а</w>', 132],
 ['м', 'и', 'н', 'д', 'а', 'ль</w>', 131],
 ['к', 'ук', 'у', 'р', 'у', 'з', 'а</w>', 125],
 ['с', 'в', 'ё', 'к', 'л', 'а</w>', 118],
 ['ц', 'е', 'д', 'р', 'а</w>', 'ли', 'м', 'о', 'н', '</w>', 118],
 ['а', 'пе', 'ль', 'с', 'и', 'н', '</w>', 115],
 ['ку', 'ри', 'ц', 'а</w>', 112],
 ['ф', 'ас', 'о', 'ль</w>', 112],
 ['к', 'о', 'ри', 'а', 'н', 'д', 'р', '</w>', 110],
 ['л', 'ук', '</w>', 'к', 'р', 'ас', 'ный</w>', 110],
 ['к', 'и', 'н', 'з', 'а</w>', 108],
 ['х', 'л', 'е', 'б', '</w>', 108],
 ['ш', 'ок', 'о', 'л', 'а', 'д', '</w>', 'м', 'о', 'л', 'о', 'чный</w>', 108],
 ['г',
  'о',
  'р',
  'о',
  'ш',
  'е',
  'к',
  '</w>',
  'з',
  'е',
  'л',
  'ё',
  'ный</w>',
  105],
 ['к', 'ре', 'в', 'е', 'т', 'к', 'а</w>', 104],
 ['о', 'ре', 'х', '</w>', 'м', 'у', 'с', 'к', 'а', 'т', 'ный</w>', 104],
 ['в', 'и', 'ш', 'н', 'я', '</w>', 101],
 ['м', 'я', 'с', 'о</w>', 101],
 ['р', 'ы', 'б', 'а</w>', 101],
 ['со', 'у', 'с', '</w>', 98],
 ['х',
  'л',
  'о',
  'п',
  'ь',
  'я',
  '</w>',
  'о',
  'в',
  'с',
  'я',
  'н',
  'о',
  'й</w>',
  97],
 ['г', 'о', 'в', 'я', 'д', 'и', 'н', 'а</w>', 96],
 ['к', 'е', 'т', 'ч', 'у', 'п', '</w>', 94],
 ['с',
  'т',
  'р',
  'у',
  'ж',
  'к',
  'а</w>',
  'к',
  'ок',
  'о',
  'со',
  'в',
  'ый</w>',
  93],
 ['с',
  'ы',
  'р',
  '</w>',
  'г',
  'о',
  'л',
  'л',
  'а',
  'н',
  'д',
  'с',
  'к',
  'и',
  'й</w>',
  93],
 ['п',
  'о',
  'м',
  'и',
  'д',
  'о',
  'р',
  'ы',
  '</w>',
  'ч',
  'е',
  'р',
  'ри',
  '</w>',
  90],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'ук',
  'у',
  'р',
  'у',
  'з',
  'ный</w>',
  86],
 ['к', 'л', 'у', 'б', 'ни', 'к', 'а</w>', 84],
 ['о', 'ре', 'х', '</w>', 84],
 ['м', 'я', 'т', 'ый</w>', 83],
 ['с',
  'е',
  'ль',
  'д',
  'е',
  'ре',
  'й</w>',
  'ч',
  'е',
  'ре',
  'ш',
  'к',
  'о',
  'в',
  'ый</w>',
  82],
 ['к', 'о', 'л', 'б', 'ас', 'а</w>', 80],
 ['м', 'а', 'к', '</w>', 80],
 ['пе', 'ч', 'е', 'ни', 'е', '</w>', 80],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'пе', 'ре', 'ц', '</w>', 80],
 ['в', 'е', 'т', 'ч', 'и', 'н', 'а</w>', 79],
 ['в',
  'и',
  'н',
  'о</w>',
  'б',
  'е',
  'л',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й</w>',
  79],
 ['ч', 'е', 'р', 'н', 'о', 'с', 'ли', 'в', '</w>', 79],
 ['г', 'в', 'о', 'з', 'д', 'и', 'к', '</w>', 78],
 ['б', 'е', 'к', 'о', 'н', '</w>', 76],
 ['к',
  'р',
  'а',
  'б',
  'о',
  'в',
  'ы',
  'е',
  '</w>',
  'п',
  'а',
  'л',
  'о',
  'ч',
  'к',
  'а</w>',
  76],
 ['т', 'и', 'м', 'ь', 'я', 'н', '</w>', 73],
 ['с',
  'а',
  'х',
  'ар',
  '</w>',
  'т',
  'р',
  'о',
  'с',
  'т',
  'ни',
  'к',
  'о',
  'в',
  'ый</w>',
  72],
 ['р', 'о', 'з', 'м', 'ар', 'и', 'н', '</w>', 68],
 ['к',
  'р',
  'а',
  'х',
  'м',
  'а',
  'л',
  '</w>',
  'к',
  'ар',
  'т',
  'о',
  'ф',
  'е',
  'ль',
  'ный</w>',
  67],
 ['к', 'р', 'у', 'п', 'а</w>', 'г', 'ре', 'ч', 'н', 'е', 'в', 'ый</w>', 67],
 ['л', 'ук', '-', 'п', 'о', 'ре', 'й</w>', 66],
 ['с', 'ы', 'р', '</w>', 'п', 'л', 'а', 'в', 'л', 'е', 'ный</w>', 66],
 ['м',
  'а',
  'к',
  'ар',
  'о',
  'н',
  'н',
  'ы',
  'е',
  '</w>',
  'и',
  'з',
  'д',
  'е',
  'ли',
  'е',
  '</w>',
  65],
 ['мас', 'ли', 'н', 'а</w>', 64],
 ['а', 'н', 'а', 'н', 'ас', '</w>', 63],
 ['к', 'о', 'н', 'ь', 'я', 'к', '</w>', 63],
 ['ш', 'п', 'и', 'н', 'а', 'т', '</w>', 62],
 ['с', 'ы', 'р', '</w>', 'т', 'в', 'о', 'р', 'о', 'ж', 'ный</w>', 59],
 ['т', 'е', 'с', 'т', 'о</w>', 'с', 'л', 'о', 'ё', 'ный</w>', 59],
 ['в', 'а', 'ре', 'ни', 'е', '</w>', 58],
 ['к', 'ар', 'ри', '</w>', 58],
 ['ку', 'р', 'ку', 'м', 'а</w>', 58],
 ['ку', 'р', 'а', 'г', 'а</w>', 56],
 ['о', 'ре', 'г', 'а', 'н', 'о</w>', 55],
 ['п', 'ар', 'м', 'е', 'з', 'а', 'н', '</w>', 55],
 ['т', 'м', 'и', 'н', '</w>', 55],
 ['ш', 'ок', 'о', 'л', 'а', 'д', '</w>', 'б', 'е', 'л', 'ый</w>', 55],
 ['к', 'а', 'п', 'у', 'с', 'т', 'а</w>', 'ц', 'в', 'е', 'т', 'ный</w>', 54],
 ['ц', 'е', 'д', 'р', 'а</w>', 'а', 'пе', 'ль', 'с', 'и', 'н', 'а</w>', 54],
 ['г', 'р', 'у', 'ш', 'а</w>', 53],
 ['л', 'ук', '</w>', 'б', 'е', 'л', 'ый</w>', 53],
 ['о', 'ли', 'в', 'к', 'и', '</w>', 'з', 'е', 'л', 'ё', 'ный</w>', 53],
 ['с', 'а', 'ло</w>', 53],
 ['со',
  'д',
  'а</w>',
  'г',
  'а',
  'ш',
  'е',
  'н',
  'а',
  'я',
  '</w>',
  'ук',
  'с',
  'у',
  'с',
  '</w>',
  53],
 ['со', 'к', '</w>', 'а', 'пе', 'ль', 'с', 'и', 'н', 'о', 'в', 'ый</w>', 53],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а</w>',
  'пе',
  'к',
  'и',
  'н',
  'с',
  'к',
  'и',
  'й</w>',
  52],
 ['пе', 'ре', 'ц', '</w>', 'с', 'л', 'а', 'д', 'к', 'и', 'й</w>', 52],
 ['д', 'ж', 'е', 'м', 'а</w>', 51],
 ['к', 'л', 'ю', 'к', 'в', 'а</w>', 51],
 ['с', 'ы', 'р', '</w>', 'с', 'ли', 'в', 'о', 'чный</w>', 51],
 ['к', 'а', 'ль', 'м', 'ар', '</w>', 50],
 ['с', 'ы', 'р', '</w>', 'м', 'я', 'г', 'к', 'и', 'й</w>', 50],
 ['о',
  'г',
  'у',
  'ре',
  'ц',
  '</w>',
  'м',
  'ар',
  'и',
  'н',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  49],
 ['пе', 'ч', 'е', 'н', 'ь', '</w>', 'ку', 'ри', 'ный</w>', 48],
 ['с', 'е', 'ль', 'д', 'ь', '</w>', 48],
 ['ф', 'и', 'л', 'е', '</w>', 'р', 'ы', 'б', 'ный</w>', 47],
 ['а', 'в', 'ок', 'а', 'д', 'о</w>', 46],
 ['о', 'ре', 'х', 'и', '</w>', 'к', 'е', 'д', 'р', 'о', 'в', 'ый</w>', 46],
 ['пе',
  'ре',
  'ц',
  '</w>',
  'с',
  'л',
  'а',
  'д',
  'к',
  'и',
  'й</w>',
  'к',
  'р',
  'ас',
  'ный</w>',
  46],
 ['л', 'а', 'в', 'а', 'ш', '</w>', 43],
 ['м', 'о', 'ц', 'а', 'ре', 'л', 'л', 'а</w>', 42],
 ['пе', 'ре', 'ц', '</w>', 'б', 'е', 'л', 'ый</w>', 42],
 ['и', 'н', 'д', 'е', 'й', 'к', 'а</w>', 41],
 ['ли', 'к', 'ё', 'р', '</w>', 41],
 ['ок', 'о', 'р', 'о', 'ч', 'ок', '</w>', 'ку', 'ри', 'ный</w>', 41],
 ['б', 'а', 'т', 'о', 'н', '</w>', 40],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'р',
  'ас',
  'т',
  'в',
  'о',
  'ри',
  'м',
  'ый</w>',
  40],
 ['м',
  'ук',
  'а</w>',
  'ц',
  'е',
  'ль',
  'н',
  'о',
  'з',
  'е',
  'р',
  'н',
  'о',
  'в',
  'ый</w>',
  40],
 ['б', 'р', 'ок', 'к', 'о', 'ли', '</w>', 39],
 ['к', 'ар', 'д', 'а', 'м', 'о', 'н', '</w>', 39],
 ['к', 'и', 'с', 'л', 'о', 'т', 'а</w>', 'ли', 'м', 'о', 'н', 'ный</w>', 39],
 ['м', 'ук', 'а</w>', 'р', 'ж', 'а', 'н', 'о', 'й</w>', 39],
 ['м', 'а', 'ли', 'н', 'а</w>', 38],
 ['ре', 'д', 'и', 'с', '</w>', 38],
 ['со', 'с', 'и', 'с', 'к', 'а</w>', 38],
 ['ф',
  'ас',
  'о',
  'ль</w>',
  'к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'и',
  'р',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  38],
 ['ч', 'е', 'ч', 'е', 'в', 'и', 'ц', 'а</w>', 38],
 ['ар', 'а', 'х', 'и', 'с', '</w>', 37],
 ['в', 'о', 'д', 'к', 'а</w>', 37],
 ['я', 'г', 'о', 'д', 'а</w>', 37],
 ['б', 'р', 'ы', 'н', 'з', 'а</w>', 36],
 ['п',
  'о',
  'р',
  'о',
  'ш',
  'ок',
  '</w>',
  'ч',
  'е',
  'с',
  'н',
  'о',
  'чный</w>',
  36],
 ['к', 'и', 'в', 'и', '</w>', 35],
 ['со', 'к', '</w>', 35],
 ['с', 'ы', 'р', 'ок', '</w>', 'п', 'л', 'а', 'в', 'л', 'ё', 'ный</w>', 35],
 ['ф', 'ар', 'ш', '</w>', 'ку', 'ри', 'ный</w>', 35],
 ['в', 'а', 'ни', 'ль</w>', 34],
 ['с', 'у', 'х', 'ар', 'и', 'к', '</w>', 34],
 ['б', 'е', 'д', 'р', 'о</w>', 'ку', 'ри', 'ный</w>', 33],
 ['з', 'и', 'р', 'а</w>', 33],
 ['пе', 'р', 'с', 'и', 'к', '</w>', 33],
 ['ф',
  'ас',
  'о',
  'ль</w>',
  'с',
  'т',
  'р',
  'у',
  'ч',
  'к',
  'о',
  'в',
  'ый</w>',
  33],
 ['х', 'м', 'е', 'ль', '-', 'с', 'у', 'н', 'е', 'ль</w>', 33],
 ['ц', 'ук', 'а', 'т', '</w>', 33],
 ['а', 'б', 'ри', 'к', 'о', 'с', '</w>', 32],
 ['к',
  'о',
  'н',
  'с',
  'е',
  'р',
  'в',
  'ы',
  '</w>',
  'р',
  'ы',
  'б',
  'ный</w>',
  32],
 ['м', 'ук', 'а</w>', 'к', 'ук', 'у', 'р', 'у', 'з', 'ный</w>', 32],
 ['н', 'у', 'т', '</w>', 32],
 ['с', 'ли', 'в', 'а</w>', 32],
 ['в', 'и', 'н', 'о', 'г', 'р', 'а', 'д', '</w>', 31],
 ['л', 'о', 'со', 'с', 'ь', '</w>', 31],
 ['б', 'ар', 'а', 'ни', 'н', 'а</w>', 30],
 ['г', 'о', 'л', 'е', 'н', 'ь', '</w>', 'ку', 'ри', 'ный</w>', 30],
 ['к',
  'о',
  'ф',
  'е',
  '</w>',
  'н',
  'а',
  'т',
  'у',
  'р',
  'а',
  'ль',
  'ный</w>',
  30],
 ['о', 'г', 'у', 'ре', 'ц', '</w>', 'со', 'л', 'ё', 'ный</w>', 30],
 ['т', 'у', 'н', 'е', 'ц', '</w>', 30],
 ['ф', 'у', 'н', 'д', 'ук', '</w>', 30],
 ['г', 'р', 'у', 'д', 'и', 'н', 'к', 'а</w>', 29],
 ['пе', 'ч', 'е', 'н', 'ь', '</w>', 'г', 'о', 'в', 'я', 'ж', 'и', 'й</w>', 29],
 ['р', 'о', 'м', '</w>', 29],
 ['с', 'ё', 'м', 'г', 'а</w>', 29],
 ['т',
  'о',
  'м',
  'а',
  'т',
  'ы',
  '</w>',
  'в',
  '</w>',
  'со',
  'б',
  'с',
  'т',
  'в',
  'е',
  'н',
  'н',
  'о',
  'м',
  '</w>',
  'со',
  'к',
  'а</w>',
  29],
 ['в',
  'и',
  'н',
  'о</w>',
  'к',
  'р',
  'ас',
  'н',
  'о',
  'е',
  '</w>',
  'с',
  'у',
  'х',
  'о',
  'й</w>',
  28],
 ['з', 'а', 'к', 'в', 'ас', 'к', 'а</w>', 28],
 ['м', 'а', 'н', 'д', 'ар', 'и', 'н', '</w>', 28],
 ['масло</w>', 'ку', 'н', 'ж', 'у', 'т', 'ный</w>', 28],
 ['ж', 'е', 'л', 'е', '</w>', 27],
 ['к',
  'р',
  'ас',
  'и',
  'т',
  'е',
  'ль</w>',
  'п',
  'и',
  'щ',
  'е',
  'в',
  '</w>',
  27],
 ['масло</w>', 'т', 'о', 'п', 'л', 'ё', 'ный</w>', 27],
 ['п',
  'о',
  'с',
  'ы',
  'п',
  'к',
  'а</w>',
  'к',
  'о',
  'н',
  'д',
  'и',
  'т',
  'е',
  'р',
  'с',
  'к',
  'и',
  'й</w>',
  27],
 ['с', 'м', 'е', 'с', 'ь', '</w>', 'с', 'пе', 'ц', 'и', 'я', '</w>', 27],
 ['со', 'к', '</w>', 'т', 'о', 'м', 'а', 'т', 'ный</w>', 26],
 ['ш', 'а', 'ф', 'р', 'а', 'н', '</w>', 26],
 ['к', 'р', 'ы', 'ль', 'я', '</w>', 'ку', 'ри', 'ный</w>', 25],
 ['п', 'ш', 'е', 'н', 'о</w>', 25],
 ['с', 'ы', 'в', 'о', 'р', 'о', 'т', 'к', 'а</w>', 25],
 ['ф', 'е', 'т', '</w>', 25],
 ['б', 'р', 'у', 'с', 'ни', 'к', 'а</w>', 24],
 ['л', 'а', 'й', 'м', '</w>', 24],
 ['о', 'в', 'о', 'щ', '</w>', 24],
 ['со', 'у', 'с', '-', 'м', 'ар', 'и', 'н', 'а', 'д', '</w>', 24],
 ['т',
  'е',
  'с',
  'т',
  'о</w>',
  'с',
  'л',
  'о',
  'е',
  'н',
  'о',
  'е',
  '</w>',
  'б',
  'е',
  'з',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  24],
 ['ф', 'и', 'ни', 'к', '</w>', 24],
 ['ф', 'о', 'ре', 'ль</w>', 24],
 ['х', 'ре', 'н', '</w>', 24],
 ['к', 'р', 'у', 'п', 'а</w>', 'пе', 'р', 'л', 'о', 'в', 'ый</w>', 23],
 ['с',
  'е',
  'ль',
  'д',
  'е',
  'ре',
  'й</w>',
  'к',
  'о',
  'р',
  'н',
  'е',
  'в',
  '</w>',
  23],
 ['с',
  'е',
  'м',
  'е',
  'ч',
  'к',
  'и',
  '</w>',
  'п',
  'о',
  'д',
  'со',
  'л',
  'н',
  'у',
  'х',
  '</w>',
  23],
 ['с',
  'м',
  'о',
  'р',
  'о',
  'д',
  'и',
  'н',
  'а</w>',
  'ч',
  'е',
  'р',
  'ный</w>',
  23],
 ['т',
  'е',
  'с',
  'т',
  'о</w>',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  23],
 ['б', 'а', 'ль', 'з', 'а', 'м', 'и', 'к', '</w>', 22],
 ['ку', 'с', '-', 'ку', 'с', '</w>', 22],
 ['с',
  'ы',
  'р',
  '</w>',
  'п',
  'о',
  'л',
  'у',
  'т',
  'в',
  'е',
  'р',
  'д',
  'ый</w>',
  22],
 ['т', 'е', 'л', 'я', 'т', 'и', 'н', 'а</w>', 22],
 ['ц', 'ук', 'к', 'и', 'н', 'я', '</w>', 22],
 ['я', 'й', 'ц', 'о</w>', 'пе', 'ре', 'пе', 'ли', 'ный</w>', 22],
 ['и', 'к', 'р', 'а</w>', 'к', 'р', 'ас', 'ный</w>', 21],
 ['к', 'а', 'пе', 'р', 'с', '</w>', 21],
 ['ф', 'р', 'ук', 'т', '</w>', 21],
 ['б', 'ли', 'н', '</w>', 20],
 ['л', 'а', 'п', 'ш', 'а</w>', 20],
 ['мас', 'к', 'ар', 'п', 'о', 'н', '</w>', 20],
 ['м', 'о', 'р', 'о', 'ж', 'е', 'н', 'о', 'е', '</w>', 20],
 ['о', 'ли', 'в', 'к', 'и', '</w>', 'ч', 'е', 'р', 'ный</w>', 20],
 ['о', 'т', 'р', 'у', 'б', 'и', '</w>', 20],
 ['т',
  'е',
  'с',
  'т',
  'о</w>',
  'с',
  'л',
  'о',
  'е',
  'н',
  'о',
  'е',
  '</w>',
  'д',
  'р',
  'о',
  'ж',
  'ж',
  'е',
  'в',
  'о',
  'й</w>',
  20],
 ['ч', 'а', 'й</w>', 'ч', 'ё', 'р', 'ный</w>', 20],
 ['г', 'о', 'р', 'б', 'у', 'ш', 'а</w>', 19],
 ['р', 'ук', 'к', 'о', 'л', 'а</w>', 19],
 ['с', 'е', 'м', 'е', 'н', 'а</w>', 'ль', 'ный</w>', 19],
 ['с', 'ку', 'м', 'б', 'ри', 'я', '</w>', 19],
 ['ч', 'е', 'р', 'ни', 'к', 'а</w>', 19],
 ['г', 'р', 'а', 'н', 'а', 'т', '</w>', 18],
 ['ку', 'б', 'и', 'к', '</w>', 'б', 'у', 'ль', 'о', 'н', 'ный</w>', 18],
 ['л', 'ук', '-', 'ш', 'а', 'л', 'о', 'т', '</w>', 18],
 ['пе', 'ре', 'ц', '</w>', 'к', 'а', 'й', 'е', 'н', 'а</w>', 18],
 ['п', 'и', 'в', 'о</w>', 'с', 'в', 'е', 'т', 'л', 'ый</w>', 18],
 ['с', 'у', 'х', 'о', 'ф', 'р', 'ук', 'т', 'ы', '</w>', 18],
 ['с',
  'ы',
  'р',
  '</w>',
  'а',
  'д',
  'ы',
  'г',
  'е',
  'й',
  'с',
  'к',
  'и',
  'й</w>',
  18],
 ['с', 'ы', 'р', '</w>', 'г', 'о', 'л', 'у', 'б', 'а</w>', 18],
 ['в',
  'а',
  'ни',
  'ль',
  'н',
  'а',
  'я',
  '</w>',
  'э',
  'с',
  'с',
  'е',
  'н',
  'ц',
  'и',
  'я',
  '</w>',
  17],
 ['г', 'о', 'р', 'о', 'х', '</w>', 17],
 ['з',
  'а',
  'г',
  'у',
  'с',
  'т',
  'и',
  'т',
  'е',
  'ль</w>',
  'д',
  'л',
  'я',
  '</w>',
  'с',
  'ли',
  'в',
  'к',
  'а</w>',
  17],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а</w>',
  'к',
  'р',
  'ас',
  'н',
  'ок',
  'о',
  'ч',
  'а',
  'т',
  'ь',
  '</w>',
  17],
 ['к', 'о', 'р', 'ж', '</w>', 17],
 ['п', 'р', 'я', 'н', 'о', 'с', 'т', 'ь', '</w>', 17],
 ['щ', 'а', 'в', 'е', 'ль</w>', 17],
 ['а', 'д', 'ж', 'и', 'к', 'а</w>', 16],
 ['м', 'и', 'д', 'и', 'я', '</w>', 16],
 ['м', 'о', 'л', 'ок', 'о</w>', 'с', 'у', 'х', 'о', 'й</w>', 16],
 ['м', 'ук', 'а</w>', 'м', 'и', 'н', 'д', 'а', 'ль', 'ный</w>', 16],
 ['м', 'ук', 'а</w>', 'ри', 'со', 'в', 'ый</w>', 16],
 ['п', 'у', 'д', 'и', 'н', 'г', '</w>', 'в', 'а', 'ни', 'ль', 'ный</w>', 16],
 ['со',
  'к',
  '</w>',
  'с',
  'в',
  'е',
  'ж',
  'е',
  'в',
  'ы',
  'ж',
  'а',
  'т',
  'ь',
  '</w>',
  16],
 ['со', 'у', 'с', '</w>', 'т', 'о', 'м', 'а', 'т', 'ный</w>', 16],
 ['у', 'т', 'к', 'а</w>', 16],
 ['ф', 'и', 'с', 'т', 'а', 'ш', 'к', 'а</w>', 16],
 ['б', 'а', 'г', 'е', 'т', '</w>', 15],
 ['г', 'л', 'а', 'з', 'у', 'р', 'ь', '</w>', 15],
 ['ж', 'и', 'р', '</w>', 15],
 ['к', 'о', 'л', 'б', 'ас', 'к', 'а</w>', 15],
 ['к', 'о', 'р', 'ни', 'ш', 'о', 'н', '</w>', 15],
 ['ку', 'м', 'и', 'н', 'а</w>', 15],
 ['ре', 'б', 'р', 'а</w>', 'с', 'в', 'и', 'н', 'о', 'й</w>', 15],
 ['ри', 'к', 'о', 'т', 'т', '</w>', 15],
 ['с', 'е', 'р', 'д', 'е', 'ч', 'к', 'и', '</w>', 'ку', 'ри', 'ный</w>', 15],
 ['с', 'п', 'а', 'г', 'е', 'т', 'т', 'и', '</w>', 15],
 ['т', 'о', 'м', 'а', 'т', 'ы', '</w>', 'в', 'я', 'л', 'ё', 'ный</w>', 15],
 ['в',
  'о',
  'д',
  'а</w>',
  'г',
  'а',
  'з',
  'и',
  'р',
  'о',
  'в',
  'а',
  'т',
  'ь',
  '</w>',
  14],
 ['и', 'н', 'ж', 'и', 'р', '</w>', 14],
 ['к',
  'а',
  'п',
  'у',
  'с',
  'т',
  'а</w>',
  'к',
  'в',
  'а',
  'ш',
  'е',
  'ный</w>',
  14],
 ['к', 'ре', 'м', '</w>', 14],
 ['м', 'ук', 'а</w>', 'о', 'в', 'с', 'я', 'ный</w>', 14],
 ['о', 'ре', 'х', 'и', '</w>', 'к', 'е', 'ш', 'ь', 'ю', '</w>', 14],
 ['ре', 'д', 'ь', 'к', 'а</w>', 14],
 ['с', 'у', 'х', 'ар', 'ь', '</w>', 14],
 ['ук',
  'с',
  'у',
  'с',
  'н',
  'а',
  'я',
  '</w>',
  'э',
  'с',
  'с',
  'е',
  'н',
  'ц',
  'и',
  'я',
  '</w>',
  14],
 ['х', 'л', 'е', 'б', 'е', 'ц', '</w>', 14],
 ['м', 'а', 'й', 'о', 'р', 'а', 'н', '</w>', 13],
 ['м', 'о', 'л', 'ок', 'о</w>', 'к', 'ок', 'о', 'со', 'в', 'ый</w>', 13],
 ['п', 'ас', 'т', 'а</w>', 13],
 ['с', 'и', 'р', 'о', 'п', '</w>', 'с', 'а', 'х', 'ар', 'ный</w>', 13],
 ['с',
  'м',
  'о',
  'р',
  'о',
  'д',
  'и',
  'н',
  'а</w>',
  'к',
  'р',
  'ас',
  'ный</w>',
  13],
 ['со', 'к', '</w>', 'я', 'б', 'л', 'о', 'чный</w>', 13],
 ['т', 'ре', 'с', 'к', '</w>', 13],
 ['в',
  'и',
  'н',
  'о</w>',
  'б',
  'е',
  'л',
  'о',
  'е',
  '</w>',
  'п',
  'о',
  'л',
  'у',
  'с',
  'л',
  'а',

* Чем больше n
  - меньше токенов в тексте
  - чаще появляются целые слова
  - словарь раздувается
  - хуже обобщение на новые слова
* Чем меньше n
  - маленький словарь
  - лучше морфологическое обобщение
  - текст длиннее
  - больше шагов для модели

## BertTokenizer

In [39]:
tokenizer = BertTokenizer.from_pretrained(
    "bert-base-multilingual-cased"
)

'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-multilingual-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 47b58cad-51d8-424a-a7b2-31e70486aa49)')' thrown while requesting HEAD https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-multilingual-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 769c07d8-e4a8-4c67-b90a-2e0b99f2e69b)')' thrown while requesting HEAD https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json
Retrying in 2s [Retry 2/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-multilingual-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 813f7d61-414c-4dc3-b7f6-36d6d1eecb6b)')' thrown while requesting HEAD https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json
Retrying in 4s [Retry 3/5].
'(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /bert-base-multilingual-cased/resolve/main/tokenizer_config.json (Caused by NameResolutionError("HTTPSConnection(host=\'huggingface.co\', port=443): Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 9851f99a-fb70-49d6-a4a1-febc043db0d3)')' thrown while requesting HEAD https://huggingface.co/bert-base-multilingual-cased/resolve/main/tokenizer_config.json
Retrying in 8s [Retry 4/5].

In [40]:
text = "масло сливочное"

tokens = tokenizer.tokenize(text)
print(tokens)

['ма', '##сло', 'сл', '##иво', '##чное']

In [41]:
encoded = tokenizer.encode(
    text,
    add_special_tokens=True
)


print(encoded)

[101, 97744, 55984, 52399, 72352, 67482, 102]

In [42]:
model = BertModel.from_pretrained("bert-base-multilingual-cased")

In [43]:
ingredients = ["клубника", "молоко", "сахар"]
text = ", ".join(ingredients)

inputs = tokenizer(text, return_tensors="pt")

In [44]:
inputs

{'input_ids': tensor([[   101,  16233,  14071,    117,    553,  69605,  11623,    117,  10868,
         104888,    102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

outputs.last_hidden_state → [batch_size, seq_len, hidden_size]

In [45]:
with torch.no_grad(): #не хранить градиенты
    outputs = model(**inputs)

embedding = outputs.last_hidden_state[:, 0, :]

In [46]:
embedding

tensor([[ 9.3631e-02, -1.0672e-01,  3.0365e-01,  2.1267e-01,  3.7680e-01,
          3.8497e-02,  1.2048e-01, -3.0851e-02,  8.0611e-02,  2.8533e-01,
          5.0185e-02,  1.5418e-01,  5.9505e-02,  3.0240e-01, -7.2601e-01,
         -2.8574e-01, -1.6038e-01,  3.2285e-01, -1.3725e-01,  2.0230e-01,
          2.2320e-01,  1.4192e-02, -5.1614e-01, -9.0738e-02,  1.0570e-01,
         -4.3999e-02, -4.3023e-01, -2.0169e-01,  2.4216e-01,  1.7035e-01,
          1.8687e-01, -1.2239e-01,  2.0965e-02, -1.8346e-02,  1.6845e-01,
         -6.7431e-02, -1.6433e+00, -3.1107e-01,  9.9729e-02, -8.2037e-02,
         -3.3351e-01,  2.5322e-01, -1.1198e-03,  4.1166e-02, -5.6697e-02,
          1.2303e+00, -1.0506e-01,  2.0632e-02,  1.4414e+00, -9.9963e-01,
          2.4011e-01, -6.3293e-01,  9.3214e-02, -1.6326e+00,  7.9976e-03,
          2.3857e-01, -4.2891e-02, -3.1507e-02,  3.1134e-02,  1.7240e-01,
         -9.8224e-02, -7.9554e-02,  2.5416e-01,  2.6955e-01, -3.1363e-01,
         -3.4742e-02,  4.5743e-02,  1.2256e-01,  2.1361e-02,  3.4188e-01,
         -8.2107e-02, -3.8137e-02, -5.3567e-02,  1.4879e-01, -1.5811e-01,
          4.0081e-02,  1.6368e-01, -9.3721e-02, -8.3613e-02, -9.2245e-02,
         -5.2449e-02,  4.7824e-01,  4.9577e-02,  2.8372e-01, -2.2158e-01,
         -3.1346e-01,  5.5786e-02,  6.8483e-02, -7.2296e-02,  5.4459e-02,
          4.0577e-02, -2.5735e-01, -5.5613e-01, -4.3905e-03, -2.6510e-01,
         -4.1669e-01,  1.0811e-02, -1.2117e-01,  1.0384e-01, -1.5439e-01,
         -1.5948e-01,  1.4688e+00, -9.8651e-02,  1.7367e-01, -2.8251e+00,
          6.0561e-02, -8.1366e-02, -2.2804e-01,  3.1104e-01, -3.7301e-02,
          3.7988e-01, -2.4590e-02,  2.4161e-01, -3.0215e-01, -6.0281e-02,
          5.2725e-02, -1.1841e-01, -3.3147e-01, -1.4865e-01, -1.5499e-01,
          1.9321e-01,  1.2709e-01, -1.4074e-01, -1.5772e-01, -2.8203e-02,
          1.3281e-01,  1.1828e-01,  9.2988e-02,  2.4682e-01,  8.7095e-01,
          5.9719e-02,  1.9462e+00,  3.1446e-02, -4.9940e-01,  4.1058e-01,
          1.4934e+00, -1.5552e-01,  2.3567e-02,  2.7668e-01,  3.3511e-01,
         -1.1962e-02,  2.6598e-02,  2.2358e-01, -1.8324e-01, -2.1920e-01,
         -1.3118e-01, -4.7767e-02, -1.1465e-01,  9.1543e-02,  1.9481e-02,
         -2.5514e-01, -1.7571e-01,  2.7452e-01,  2.6710e-01,  1.0209e-01,
          8.4256e-02,  2.7500e-02, -7.6863e-02,  1.9099e-01,  2.1674e-01,
          1.7640e+00,  1.7705e-01, -7.4498e-02,  1.2785e-01, -1.2490e-01,
          2.5959e-01,  1.6269e-02,  4.7014e-02, -2.7536e-01, -1.5521e-01,
         -1.9899e-01, -2.9680e-01,  1.1197e-01, -3.5356e-01, -2.3346e-02,
          1.9001e-01, -1.3491e-01,  1.1153e-01, -1.3146e-01,  9.5127e-03,
         -1.0846e-01,  1.7259e-01,  1.1138e-01,  1.8994e-01,  4.3426e-02,
         -3.1821e-03, -2.7890e-01,  1.0051e-01, -1.7176e-01, -4.9690e-01,
          5.6865e-01,  9.3282e-02,  2.6690e-01,  1.1729e-01,  2.0561e-01,
          1.9264e-01, -7.9227e-02,  3.3584e-02,  1.8917e-01,  7.5479e-02,
         -2.2952e-01,  4.5870e-01,  4.7509e-02,  8.5960e-02, -1.3100e-02,
          4.6035e-01,  1.8474e-01, -1.7545e-01,  2.2538e-01,  6.3251e-02,
         -2.8802e-02,  6.3325e-02,  1.0221e+00,  9.0533e-02, -1.4850e-01,
         -3.8091e-03,  1.1613e-01, -1.3220e-01,  5.5796e-02, -2.1542e+00,
         -7.5983e-02,  1.0930e-01,  1.8912e-01,  1.9910e-02, -6.3505e-02,
         -9.1730e-02, -1.0845e-01,  4.0241e-01,  1.0259e-01, -9.1259e-02,
          3.0766e-01, -4.4211e-01,  1.8134e-01, -1.9404e+00,  2.6700e-03,
         -5.9840e-02,  3.4700e-01, -5.8709e-02, -9.9540e-02, -5.4886e-02,
         -7.7485e-02, -9.3226e-03,  1.3081e-01, -2.2834e-01,  2.3137e-01,
         -2.9026e-01,  9.9223e-01,  1.3532e-01,  4.3593e-02, -4.1947e-01,
         -2.2048e-01, -7.1199e-02,  3.5986e-01, -4.6610e-02, -2.9321e-01,
          4.5653e-02, -1.4543e-01,  3.9576e-02,  3.9935e-01,  1.3991e-01,
         -1.2923e-01,  2.1266e-02, -5.1822e-01, -5.3506e-01,  5.0770e-02,
         -3.5811e-01,  7.3312e-02,  1.4081e-01,  8.7097e-02, -2.0698e-01,
          9.2728e-02,  4.9886e-02,  4.0687e-02,  1.6456e-01, -2.7187e-01,
          2.0603e-01,  8.6670e-02,  1.5229e-01,  9.6840e-02,  2.4457e-01,
          3.3808e-02,  4.4280e-02,  2.4192e-01,  9.4892e-03,  1.1728e-01,
          1.9192e-02,  1.2074e-02, -2.7706e-01, -8.0530e-01, -1.1144e+00,
          2.3591e-02,  1.4055e-01,  6.8466e-02, -1.3644e-01, -3.9954e-01,
         -1.4049e-01,  1.2629e-02, -1.2352e-01,  4.8222e-03, -1.6176e-01,
          1.6506e-01, -2.5467e-01,  5.1666e-02,  2.0597e-02, -1.6582e+00,
         -1.5349e-01,  8.2535e-02, -4.6765e-02,  1.5537e-01,  4.5266e-02,
         -4.4094e-01, -2.6482e-01, -2.8635e-02, -3.3160e-01, -1.9548e-01,
          4.5604e-02,  6.9882e-02,  3.8497e-01, -1.0797e-02, -3.1404e-02,
          3.6878e-02, -1.7713e+00, -5.6671e-02,  1.1261e-02,  9.7445e-02,
         -2.7005e-01, -3.1880e-01,  1.4827e-01,  2.6674e-01,  9.4298e-02,
         -1.3091e-01,  3.7759e-01,  8.5796e-02, -4.0229e-01,  7.2898e-02,
          1.0002e-01, -1.5572e-02, -1.8909e-01, -7.5624e-02,  1.4995e-02,
          9.1746e-03,  1.3753e-01, -1.2355e-01, -1.3474e-01, -7.4609e-02,
          2.9245e-01,  1.3198e-01, -2.5353e-01,  6.9405e-02,  1.4735e-01,
          3.7767e-02,  1.0046e-01, -6.7461e-01, -1.4597e-01,  8.5356e-02,
         -2.0203e-01,  1.9920e-01,  8.1623e-03,  1.8181e-01,  2.2057e-01,
         -1.6494e-01, -1.4145e-01,  1.0926e-01, -1.6522e-01, -1.7126e-01,
         -2.3886e-01,  5.8071e-02,  4.4793e-02,  3.3212e-01,  1.1511e-01,
          4.3431e-01, -6.3804e-04, -4.8780e-02, -3.0001e-01, -3.4582e-03,
          8.9849e-02,  2.5978e-01,  6.2362e-02,  1.5967e-01,  4.1968e-02,
          1.0676e-02,  1.2608e-01, -1.5921e+00,  6.3749e-02,  2.3084e-01,
         -1.5958e+00, -1.5150e-01,  7.1358e-02, -1.3336e-01, -3.2354e-01,
         -3.2142e-02,  2.4179e-02,  2.4657e-01,  1.1004e-01, -9.6529e-02,
          3.3933e-02,  3.0460e-02,  3.8794e-02,  1.8184e-01,  2.9759e-03,
          9.9089e-02, -4.1723e-01,  2.3549e-01, -2.2427e-01, -2.3713e-01,
         -1.6170e+00,  2.1278e-01,  2.5784e-01,  1.3734e-01, -2.6824e-01,
         -1.4363e-01, -1.2927e-01,  2.0014e-01,  2.1980e-01, -1.4776e-01,
          7.8837e-02, -2.8032e-01,  1.1787e-01, -3.9198e-02, -4.1626e-01,
          1.8288e-01,  6.3361e-01, -8.2180e-02, -2.1462e-01, -5.8142e-02,
          4.9823e-03,  7.7164e-02,  5.8226e-02,  1.2830e-01, -2.6060e-01,
         -2.2029e-01,  8.4700e-02,  1.7590e-01, -1.2337e+00, -2.1361e+00,
          1.0549e+00, -1.8757e-01,  2.3416e-01,  1.7540e-01,  1.8998e+00,
          9.2973e-02,  2.2816e-01, -6.7463e-02, -8.7432e-02,  1.4438e-01,
          3.1297e+00,  4.4121e-01,  1.0733e-01,  1.2212e+00,  3.2023e-01,
          1.8315e-01, -7.0720e-03, -1.6040e+00, -2.3048e+00,  6.0430e-02,
         -2.3102e-01,  8.2159e-02, -1.0109e-02, -1.1005e-01, -2.5104e-01,
          1.5081e-01,  1.3428e-01,  5.0070e-02,  8.9956e-02,  1.6495e-01,
         -3.1197e-01, -1.9457e-01,  1.4695e-02,  2.2034e-02,  1.6692e-01,
          5.6263e-01, -1.5319e-01, -6.6731e-02,  9.3929e-02, -1.0983e-01,
         -1.9230e+00,  4.7612e-02,  3.3916e-01,  3.9312e-01, -2.7258e-01,
          9.1570e-02,  1.1504e-01, -1.0937e-04, -3.6767e-01,  1.1775e-01,
          3.8756e-01,  1.7055e-01,  2.8994e-02, -1.0546e-01,  1.6594e-01,
          1.8873e-01, -5.8936e-02, -3.5453e-02,  2.1977e+00, -2.5096e-01,
         -1.0591e-01,  5.0157e-01,  1.2053e-01,  7.4756e-01, -3.4126e-01,
          1.4122e-01, -1.5685e-01,  1.0229e-01, -5.5017e-02, -1.2512e-01,
          7.8041e-02, -3.9787e-01, -1.2462e-01, -7.7952e-03,  2.8101e-01,
          5.4519e-01,  4.6598e-01,  3.3003e-02, -1.0074e+00,  2.4405e-01,
          1.4437e-01, -4.2009e-02, -2.2201e-01, -2.5197e-01, -2.5159e-02,
          3.9727e-01, -1.2940e-01,  2.4939e-03, -8.2272e-02, -5.6471e-01,
         -1.1154e-01, -1.2659e-01, -1.4705e-01, -8.9135e-02, -1.3490e-01,
         -4.8435e-01, -5.8439e-01, -1.5048e-01,  1.2569e+00,  5.7291e-02,
         -2.1795e-03,  9.7695e-01, -6.2939e-02, -1.5675e-02,  1.1644e-01,
          2.3583e-02,  7.3926e-02, -2.4408e-01, -1.9720e-01,  2.0777e-01,
          9.9387e-03,  8.6509e-02, -2.2210e-02,  3.5872e-01,  3.5738e-01,
         -6.3824e-02,  2.0968e-01, -1.6088e-02, -1.0964e-02, -3.9975e-01,
         -4.0236e-01, -4.0000e-02,  7.1603e-02, -1.6310e-01,  3.1537e-01,
          2.8897e-01,  9.9295e-02,  1.2684e-01,  3.9348e-02, -1.0400e-01,
         -9.3008e-02, -4.3241e-01,  4.0544e-01,  5.7112e-02,  3.3147e-01,
          3.4505e-02,  7.7157e-02,  4.2701e-02,  3.6688e-02, -4.3147e-02,
         -2.0136e-01, -1.2963e-01,  3.3535e-01,  1.7932e-01, -2.8766e-01,
          5.4471e-01, -7.2731e-03,  5.0760e-02,  5.1482e-02, -4.1686e-01,
          8.7665e-02, -9.6179e-02,  2.0620e-01, -2.7318e-01, -1.6496e-01,
         -1.7544e-02,  7.5122e-02,  2.6335e-01,  1.4254e-01,  2.4307e-01,
          4.2084e-01,  2.2925e-01,  8.9188e-02, -2.4096e-02,  2.9273e-02,
          3.5947e-01, -3.3475e-01,  1.4486e-01, -2.8466e-01, -2.3629e-01,
          2.0443e-01,  1.8136e-01,  2.4129e-01, -6.4617e-01,  3.3302e-01,
          2.3974e-02,  1.1427e-01, -2.9371e-01,  1.8537e-01, -1.5944e-01,
         -2.1988e+00, -2.3941e-01,  1.4504e-01,  7.4151e-02,  3.3083e-01,
          1.7356e-01,  7.6651e-01,  4.4226e-02, -2.3530e-01, -2.2980e-01,
          2.5242e-03,  1.0989e-01, -2.5818e-01, -1.7164e-01, -6.6078e-01,
          2.0316e-01, -2.5618e-01, -6.4674e-03, -1.5335e-01, -1.4910e-02,
         -1.7105e+00, -6.2971e-02, -5.8414e-02, -3.0065e-01,  3.2036e-01,
         -3.1713e-01,  1.7994e-01, -3.4890e-01, -7.5340e-02,  2.0948e-01,
         -4.3955e-01, -2.7238e-01,  1.6780e-01, -1.7276e-01,  1.9586e-01,
          1.0733e-01, -6.6226e-02,  2.1797e-02, -1.6759e-01,  3.7236e-02,
          1.1886e-01,  5.9498e-02,  6.2849e-02,  1.1173e-01,  2.8563e-01,
          2.4541e-01, -1.0209e-01,  2.9140e-01,  8.7935e-02,  1.1215e-01,
         -1.8758e+00,  2.8492e-02,  7.0830e-02, -9.0531e-02, -4.4005e-01,
          1.5903e-01, -5.6023e-02, -1.9938e-01,  3.8963e-02, -7.6846e-02,
         -7.0138e-01,  4.3035e-02,  2.2667e-01,  7.2012e-02, -1.6001e-01,
          9.8556e-02,  7.5881e-01,  2.1260e-01,  1.9518e-01,  8.5228e-03,
         -8.1347e-02, -8.1210e-02,  2.1866e-01, -7.6657e-02,  6.4624e-01,
          3.4599e-01, -7.7740e-02, -1.3802e-01, -1.0839e-01,  3.0168e-01,
         -6.4441e-03, -1.0068e+00,  2.4877e-01,  3.7141e-02,  6.1373e-02,
         -1.0376e-01, -9.5480e-02, -2.2374e-01,  3.5807e-01,  8.7712e-02,
          1.5079e-01,  5.0976e-01,  2.0705e+00,  1.8692e-01, -3.0136e-01,
          2.5512e-01,  1.3354e-01,  1.1183e-01,  3.8856e-02, -1.2327e-01,
          1.8594e+00,  1.0325e-02, -2.4001e-01, -4.9556e-03,  3.7111e-01,
          3.7514e-01,  1.3974e+00,  1.4034e-01,  2.2638e-01, -6.4798e-02,
          3.1184e-01, -2.5482e-01,  2.5187e-01,  3.3128e-02,  3.2734e-02,
          1.7036e-01, -7.4369e-01,  1.5715e-01,  1.6300e-01,  2.9978e-01,
          1.5208e-01, -5.8711e-01,  2.5082e-01, -2.3074e-01, -1.3368e-01,
         -1.3433e-01, -6.6181e-02, -2.8733e-01, -7.8325e-02,  1.2282e-01,
          7.4213e-02, -1.4121e-02,  5.1788e-02, -7.4980e-01,  1.2880e-01,
          2.8694e-01, -4.1702e-01,  1.6950e-01, -2.8405e-01, -1.8375e-02,
          7.1446e-01,  2.2392e-01, -3.2616e-02, -5.4258e-02, -8.6252e-02,
          6.5576e-02, -2.6365e-01, -9.2690e-02, -5.5587e-02,  1.0393e-01,
          7.9179e-02,  1.3674e-02,  2.4125e-02]])

In [47]:
embeddings = []
for ingredients  in df['ingredients_list']:
    text = ", ".join(ingredients)
    inputs = tokenizer(text, return_tensors="pt")

    with torch.no_grad(): #не хранить градиенты
        outputs = model(**inputs)
    embedding = outputs.last_hidden_state[:, 0, :][0]
    embeddings.append(embedding.numpy())
df['embeddings'] = embeddings

Косинусное сходство нового рецепта с каждым рецептом базы вычисляется так:

$$
\text{similarities}[i] = \frac{a \cdot b_i}{\|a\| \, \|b_i\|}, \quad \forall i = 1, \dots, N
$$

1 → векторы максимально похожи

0 → нейтрально, не похожи

-1 → противоположны

## WORD2VEC

In [51]:
recipes = df['ingredients_list'].tolist()

In [52]:
from gensim.models import Word2Vec

model = Word2Vec(
    sentences=recipes,
    vector_size=100,   # сколько признаков описывает слово
    window=5,          # сколько слов считается контекстом
    min_count=2,       # минимальное число вхождений слова
    sg=1,              # Skip-gram - угадывает контекст по слову
    workers=4,         # число потоков CPU
    epochs=20
)

In [53]:
model.wv # - эмбединги

In [118]:
salad_vec = model.wv['салат']

KeyError: "Key 'салат' not present"

In [55]:
recipe_names = df['name'].to_list()

In [56]:
def recipe_embedding(recipe, model):
    vecs = [model.wv[w] for w in recipe if w in model.wv]
    return np.mean(vecs, axis=0)

In [57]:
recipe_vectors = np.array([recipe_embedding(r, model) for r in recipes])

In [58]:

pca = PCA(n_components=3)
reduced = pca.fit_transform(recipe_vectors)

fig = px.scatter_3d(
    x=reduced[:,0],
    y=reduced[:,1],
    z=reduced[:,2],
    hover_name=recipe_names,
    size_max=5,
    title="3D визуализация пространства рецептов"
)
fig.show()

Выглядит похожим на правду.

In [59]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def find_similar_recipes_by_vectors(df, recipe_vectors, recipe_idx, top_n=10):

    # Вектор выбранного рецепта
    new_embedding = recipe_vectors[recipe_idx].reshape(1, -1)

    similarities = cosine_similarity(new_embedding, recipe_vectors).flatten()

    # - сам рецепт
    similarities[recipe_idx] = -1

    # индексы топ
    top_idx = similarities.argsort()[-top_n:][::-1]

    #  топ-n рецептов
    top_recipes = df.iloc[top_idx].copy()
    top_recipes['similarity'] = similarities[top_idx]  # косинусная похожесть

    print(f"Выбранный рецепт (индекс {recipe_idx}):")
    print(f"Название: {df.loc[recipe_idx, 'name']}")
    print(f"Ингредиенты: {df.loc[recipe_idx, 'ingredients_list']}\n")

    print(f"Топ-{top_n} похожих рецептов:")
    for i, row in top_recipes.iterrows():
        print(f"{i}. {row['name']} (Схожесть: {row['similarity']:.3f})")
        print(f"   Ингредиенты: {row['ingredients_list']}\n")

    return top_recipes

In [60]:
top = find_similar_recipes_by_vectors(df, recipe_vectors, recipe_idx=278, top_n=5)

Выбранный рецепт (индекс 278):
Название: Мясо на водяной бане с травами
Ингредиенты: ['вода', 'гвоздика', 'зелень', 'лук репчатый', 'мука ржаная', 'мясо', 'перец черный', 'соль']

Топ-5 похожих рецептов:
1356. Салма баранья (Схожесть: 0.953)
   Ингредиенты: ['баранина', 'вода', 'картофель', 'лист лавровый', 'лук репчатый', 'мука пшеничная', 'перец черный', 'соль']

4718. Гарнир из запаренной гречки (Схожесть: 0.953)
   Ингредиенты: ['вода', 'зелень', 'крупа гречневая', 'лук белый', 'соль', 'тыква']

3997. Рыжики в томате (Схожесть: 0.952)
   Ингредиенты: ['вода', 'грибы', 'лист лавровый', 'лук репчатый', 'масло растительное', 'морковь', 'перец черный', 'сахар', 'соль', 'томатная паста']

2119. Гороховый суп с бараниной в мультиварке (Схожесть: 0.950)
   Ингредиенты: ['баранина', 'вода', 'горох', 'зелень', 'картофель', 'лист лавровый', 'лук репчатый', 'масло растительное', 'морковь', 'сельдерей корневой', 'соль']

5437. Рис с индейкой и сушеной вишней (Схожесть: 0.949)
   Ингредиенты: ['вишня', 'вода', 'зелень', 'индейка', 'лук репчатый', 'масло растительное', 'морковь', 'приправа', 'рис', 'соль', 'шафран']

тут видно. что самым похожим блюдом Мясо на водяной бане с травами он считает блюдо Салма баранья. Хотя в первом написано Мясо, а во втором Баранина. Также в первом 'мука ржаная' а во втором 'мука пшеничная'

In [61]:
top = find_similar_recipes_by_vectors(df, recipe_vectors, recipe_idx=31, top_n=5)

Выбранный рецепт (индекс 31):
Название: Лeгкий Рыбно-Овощной Салат
Ингредиенты: ['авокадо', 'зелень', 'капуста пекинская', 'консервы рыбные', 'креветки', 'лимон', 'масло оливковое', 'специи']

Топ-5 похожих рецептов:
3687. Салат "Праздничный" из креветок и авокадо (Схожесть: 0.948)
   Ингредиенты: ['авокадо', 'капуста пекинская', 'креветки', 'лимон', 'листья салата', 'масло оливковое', 'соль']

1183. Салат  «Русалка» (Схожесть: 0.944)
   Ингредиенты: ['горчица', 'капуста краснокочанная', 'капуста морская', 'киви', 'креветки', 'масло оливковое', 'мед', 'сок лимонный', 'специи', 'сыр твердый', 'тунец']

3183. Салат "Морское чудо" (Схожесть: 0.944)
   Ингредиенты: ['булочка', 'консервы рыбные', 'корнишоны', 'креветки', 'майонез', 'масло растительное', 'оливки черные', 'приправа', 'яйцо куриное']

1464. Салат с крабовыми палочками и кус-кусом (Схожесть: 0.940)
   Ингредиенты: ['авокадо', 'горчица', 'зелень', 'крабовые палочки', 'кус-кус', 'масло оливковое', 'огурец', 'помидор', 'помидоры черри', 'приправа', 'сметана', 'сок лимонный']

3156. Крабовый салат по-новому (Схожесть: 0.938)
   Ингредиенты: ['икра красная', 'крабовые палочки', 'креветки', 'кукуруза', 'лук зеленый', 'майонез', 'масло кунжутное', 'мидии', 'пармезан', 'рис', 'соевый соус', 'яйцо куриное']

тут четко сработано. салат похож на салат. и при этом все с морской тематикой

In [62]:
top = find_similar_recipes_by_vectors(df, recipe_vectors, recipe_idx=1070, top_n=5)

Выбранный рецепт (индекс 1070):
Название: Торт с клубникой, ревенем и кремом
Ингредиенты: ['бисквит', 'клубника', 'крахмал', 'миндаль', 'ревень', 'рикотта', 'сахар', 'сливки']

Топ-5 похожих рецептов:
5284. Кофейно-малиновый торт (Схожесть: 0.972)
   Ингредиенты: ['ванильная эссенция', 'вода', 'джем', 'желатин', 'кофе растворимый', 'малина', 'маскарпоне', 'мука пшеничная', 'орехи лесные', 'сахар', 'сливки', 'соль', 'шоколад белый', 'шоколад темный', 'яйцо куриное']

5571. Торт "Карибское лето" (Схожесть: 0.972)
   Ингредиенты: ['ананас', 'желе', 'загуститель для сливок', 'крахмал', 'ликер', 'маскарпоне', 'миндаль', 'мука пшеничная', 'разрыхлитель теста', 'сахар', 'сливки', 'стружка кокосовая', 'яйцо куриное']

1934. Клубнично-сливочный торт-суфле (Схожесть: 0.970)
   Ингредиенты: ['белок яичный', 'ваниль', 'вода', 'желатин', 'загуститель для сливок', 'клубника', 'молоко сгущенное', 'мука пшеничная', 'сахар', 'сахарная пудра', 'сливки', 'сок лимонный', 'соль', 'экстракт']

4118. Десерт для Снежной королевы (Схожесть: 0.969)
   Ингредиенты: ['белок яичный', 'крахмал кукурузный', 'ликер', 'маскарпоне', 'миндаль', 'мука миндальная', 'сахарная пудра', 'сливки', 'стружка кокосовая']

4370. Десерт "Мой Огород" (Схожесть: 0.969)
   Ингредиенты: ['ванильный сахар', 'джем', 'желатин', 'мята', 'печенье', 'розмарин', 'сахар', 'сливки', 'сок', 'творожная масса']

тут интересно. топ 1 похожесть (Схожесть: 0.972) блюдо, которое п освоему составву оказалось максмально непохожим на оригинальное блюдо. И логически тоже удачно получилось сопоставить

## Новый частнотный анализ

In [112]:
import plotly.graph_objects as go
def frequency_fun(title, top_n = 15):
    df_salad = df[df["name"].str.contains(title)]

    cur_ingredients = df_salad["ingredients_list"].explode()
    frequency_analysis = cur_ingredients.value_counts()


    top_ingredients = frequency_analysis.head(top_n)

    ingredient_names = top_ingredients.index.tolist()
    ingredient_counts = top_ingredients.values.tolist()

    fig = go.Figure(data=[
        go.Bar(
            x=ingredient_names,
            y=ingredient_counts,
            marker_color='lightseagreen',
            text=ingredient_counts,
            textposition='outside',
            hovertemplate='<b>%{x}</b><br>Частота: %{y}<extra></extra>'
        )
])

    fig.show()

In [113]:
frequency_fun('салат')

In [114]:
frequency_fun('пицца')

In [115]:
frequency_fun('йогурт')

## Проверка на непохожесть

In [116]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def find_most_different_recipes_by_vectors(df, recipe_vectors, recipe_idx, top_n=10, exclude_self=True):

    target_embedding = recipe_vectors[recipe_idx].reshape(1, -1)
    similarities = cosine_similarity(target_embedding, recipe_vectors).flatten()

    if exclude_self:
        similarities[recipe_idx] = 1

    most_different_idx = similarities.argsort()[:top_n]

    different_recipes = df.iloc[most_different_idx].copy()
    different_recipes['similarity'] = similarities[most_different_idx]
    different_recipes['distance'] = 1 - similarities[most_different_idx]  # косинусное расстояние

    print(f"Исходный рецепт (индекс {recipe_idx}):")
    print(f"Название: {df.loc[recipe_idx, 'name']}")
    print(f"Ингредиенты: {df.loc[recipe_idx, 'ingredients_list']}")
    print("-" * 50)

    print(f"\nТоп-{top_n} самых НЕпохожих рецептов:")
    print(f"(отсортировано по возрастанию сходства)")
    print("=" * 80)

    for i, (idx, row) in enumerate(different_recipes.iterrows(), 1):
        print(f"{i}. {row['name']}")
        print(f"   Сходство: {row['similarity']:.3f} | Расстояние: {row['distance']:.3f}")
        print(f"   Ингредиенты: {row['ingredients_list']}")
        print("-" * 40)

    return different_recipes

In [117]:
top = find_most_different_recipes_by_vectors(df, recipe_vectors, recipe_idx=1070, top_n=5)

Исходный рецепт (индекс 1070):
Название: Торт с клубникой, ревенем и кремом
Ингредиенты: ['бисквит', 'клубника', 'крахмал', 'миндаль', 'ревень', 'рикотта', 'сахар', 'сливки']
--------------------------------------------------

Топ-5 самых НЕпохожих рецептов:
(отсортировано по возрастанию сходства)
================================================================================
1. Рагу
   Сходство: 0.238 | Расстояние: 0.762
   Ингредиенты: ['лук репчатый', 'морковь', 'овощи', 'огурец', 'перец болгарский', 'помидор']
----------------------------------------
2. Салат "Деревенский"
   Сходство: 0.241 | Расстояние: 0.759
   Ингредиенты: ['майонез', 'морковь', 'огурец соленый', 'сухарики']
----------------------------------------
3. Салат из куриных сердечек с луком
   Сходство: 0.244 | Расстояние: 0.756
   Ингредиенты: ['лук репчатый', 'майонез', 'сердечки куриные']
----------------------------------------
4. Цветы из острого перца
   Сходство: 0.247 | Расстояние: 0.753
   Ингредиенты: ['лук-порей', 'перец красный жгучий']
----------------------------------------
5. Овощная нарезка
   Сходство: 0.247 | Расстояние: 0.753
   Ингредиенты: ['лук зеленый', 'майонез', 'огурец', 'помидор']
----------------------------------------

In [119]:
sentences = []

for ingredients, title in zip(recipes, recipe_names):
    title_words = title.lower().split()
    sentences.append(ingredients + title_words)

model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    sg=1,
    epochs=20
)

In [125]:
import numpy as np

def recipe_embedding(recipe, title, model, alpha=0.2):
    ing_vecs = [model.wv[w] for w in recipe if w in model.wv]
    title_vecs = [model.wv[w] for w in title.lower().split() if w in model.wv]

    ing_vec = np.mean(ing_vecs, axis=0) if ing_vecs else np.zeros(model.vector_size)
    title_vec = np.mean(title_vecs, axis=0) if title_vecs else np.zeros(model.vector_size)

    return alpha * title_vec + (1 - alpha) * ing_vec


recipe_vectors = np.array([
    recipe_embedding(r, t, model)
    for r, t in zip(recipes, recipe_names)
])

In [126]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
recipe_3d = pca.fit_transform(recipe_vectors)

In [127]:
salad_vec = model.wv['салат']
salad_3d = pca.transform([salad_vec])[0]

In [128]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    recipe_vectors,
    salad_vec.reshape(1, -1)
).flatten()

In [129]:
import plotly.express as px

fig = px.scatter_3d(
    x=recipe_3d[:, 0],
    y=recipe_3d[:, 1],
    z=recipe_3d[:, 2],
    color=similarities,
    color_continuous_scale='RdYlGn_r',
    hover_name=recipe_names,
    title="Пространство рецептов: близость к слову 'салат'"
)

# точка "салат"
fig.add_scatter3d(
    x=[salad_3d[0]],
    y=[salad_3d[1]],
    z=[salad_3d[2]],
    mode='markers+text',
    marker=dict(size=8, color='black'),
    text=['салат'],
    textposition='top center',
    name='салат'
)

fig.show()