In [177]:
import pandas as pd

In [178]:
df = pd.read_csv('Wrongful Convictions in the United States.csv')

In [179]:
df = df.drop(columns=['Defendants', 'Legally Exonerated'], axis=1)
df.head(5)

,Unnamed: 0,Date of the Crime,Type of the Crime,Location of the Crime,Punishment for a crime,Legally Exonerated Encoded
0,0,1805,murder,Massachusetts,death,1
1,1,1843,murder,Rhode Island,death,1
2,2,1855,murder,Washington,death,0
3,3,1863,murder,Texas,death,1
4,4,1872,murder,Nebraska,death,1

In [180]:
df['Punishment for a crime'].unique()

array(['death', '15 years', nan, 'life in prison', '5 years',
       'life without parole', '25 years', '20 years', '50 years',
       'death for Jimerson and Williams, 75 years for Adams, and life for Rainge',
       '75 years', '30 years', '40 years', '32 years', '63 years',
       '45 years', '33 years', '35 years', '11-35 years', '84 years',
       '49 years', '10 years', '7 years', '57 years', '60 years',
       'community service', '8 years', '65 years', '55 years', '17 years',
       'probation, lifetime sex offender registration', '6 years',
       '22 years', 'present', '21 years', '0.5 years', '4 years',
       '1.2 year', '16 years', '26 years', '12.5 years', 'not sentenced',
       '9 months'], dtype=object)

In [181]:
df

,Unnamed: 0,Date of the Crime,Type of the Crime,Location of the Crime,Punishment for a crime,Legally Exonerated Encoded
0,0,1805,murder,Massachusetts,death,1
1,1,1843,murder,Rhode Island,death,1
2,2,1855,murder,Washington,death,0
3,3,1863,murder,Texas,death,1
4,4,1872,murder,Nebraska,death,1
...,...,...,...,...,...,...
173,173,2016,"robbery, other violent felony",Michigan,20 years,1
174,174,2017,sexual assault,Wisconsin,NaN,1
175,175,2017,assault,Indiana,6 years,1
176,176,2017,child sex abuse,Oregon,50 years,1
177,177,2017,arson,Wisconsin,9 months,1

In [182]:
row = df.iloc[41]
df = df.drop(df.index[41])

In [183]:
row

Unnamed: 0                                                                   41
Date of the Crime                                                          1978
Type of the Crime                                                          rape
Location of the Crime                                                  Illinois
Punishment for a crime        death for Jimerson and Williams, 75 years for ...
Legally Exonerated Encoded                                                    1
Name: 41, dtype: object

In [184]:
rows = []

for punish in [
    "death",
    "death",
    "75 years",
    "life in prison"
]:
    r = row.copy()
    r["Punishment for a crime"] = punish
    rows.append(r)

In [185]:
df = pd.concat([df, pd.DataFrame(rows)], ignore_index=True)

In [186]:
df['Type of the Crime'] = df['Type of the Crime'].replace('sabotage of Locomotive 213', 'sabotage')

In [187]:
df['Type of the Crime'].unique()

array(['murder', 'haymarket affair', 'sabotage', 'rape',
       'preparedness Day Bombing', 'breaking and entering, petty theft',
       'sexual assault', 'robbery, rape', 'murder, robbery',
       'satanic ritual sex abuse', 'rape,  murder', 'assault, rape',
       'murder, robbery, burglary', 'rape, sodomy, robbery',
       'rape, robbery', 'child sexual abuse', 'sexual abuse of children',
       'murder, robbery, illegal use of a weapon', 'murder, carjacking',
       'sexual assault, sexual abuse, kidnapping, robbery',
       'rape, kidnapping',
       'sexual assault, robbery, other violent felony',
       'drive-by shooting', 'rape, murder',
       'criminal sexual conduct, armed robbery', 'filing a false report',
       'murder, rape', 'sexual assault, kidnapping', 'child abuse',
       'manslaughter', 'manslaughter of infant', 'child sex abuse',
       'weapon possession or sale',
       'robbery, assault, illegal use of a weapon', 'robbery',
       'murder, assault, illegal use of a weapon', 'fraud',
       'felony assault of a child',
       'attempted murder, robbery, assault, kidnapping',
       'murder, other violent felony, conspiracy', 'theft',
       'murder, gun possession or sale and conspiracy', 'assault',
       'robbery, other violent felony', 'arson'], dtype=object)

In [188]:
df['Crime List'] = df['Type of the Crime'].str.split(',')

In [189]:
df['Crime List'] = df['Crime List'].apply(lambda lst: [x.strip() for x in lst])
mlb = pd.get_dummies(df['Crime List'].explode()).groupby(level=0).sum()

df = pd.concat([df.drop(columns=['Crime List']), mlb], axis=1)

In [203]:
df

,Unnamed: 0,Date of the Crime,Type of the Crime,Punishment for a crime,Legally Exonerated Encoded,armed robbery,arson,assault,attempted murder,breaking and entering,...,rape,robbery,sabotage,satanic ritual sex abuse,sexual abuse,sexual abuse of children,sexual assault,sodomy,theft,weapon possession or sale
0,0,-5.133602,murder,1.134146,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,-4.021265,murder,1.134146,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,-3.670001,murder,1.134146,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,-3.435824,murder,1.134146,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,-3.172376,murder,1.134146,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,177,1.072068,arson,-1.911450,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
177,41,-0.069541,rape,1.134146,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
178,41,-0.069541,rape,1.134146,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
179,41,-0.069541,rape,0.366993,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
180,41,-0.069541,rape,0.366993,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [191]:
df = df.drop(columns=['Location of the Crime'], axis=1)

In [192]:
df['Punishment for a crime'].unique()

array(['death', '15 years', nan, 'life in prison', '5 years',
       'life without parole', '25 years', '20 years', '50 years',
       '75 years', '30 years', '40 years', '32 years', '63 years',
       '45 years', '33 years', '35 years', '11-35 years', '84 years',
       '49 years', '10 years', '7 years', '57 years', '60 years',
       'community service', '8 years', '65 years', '55 years', '17 years',
       'probation, lifetime sex offender registration', '6 years',
       '22 years', 'present', '21 years', '0.5 years', '4 years',
       '1.2 year', '16 years', '26 years', '12.5 years', 'not sentenced',
       '9 months'], dtype=object)

In [193]:
import re
import numpy as np

def punishment_to_years(x):
    if pd.isna(x):
        return np.nan
    x = x.lower().strip()

    if '-' in x:
        nums = re.findall(r'\d+\.?\d*', x)
        nums = [float(n) for n in nums]
        return np.mean(nums)

    if 'month' in x:
        num = float(re.findall(r'\d+\.?\d*', x)[0])
        return num / 12

    if 'year' in x:
        num = float(re.findall(r'\d+\.?\d*', x)[0])
        return num

    if 'death' in x:
        return 100
    if 'life' in x:
        return 75

    # особые случаи
    if 'community service' in x:
        return 1
    if 'probation' in x or 'not sentenced' in x or 'present' in x:
        return 0

    return np.nan

In [194]:
df['Punishment for a crime'] = df['Punishment for a crime'].apply(punishment_to_years)

In [195]:
df

,Unnamed: 0,Date of the Crime,Type of the Crime,Punishment for a crime,Legally Exonerated Encoded,armed robbery,arson,assault,attempted murder,breaking and entering,...,rape,robbery,sabotage,satanic ritual sex abuse,sexual abuse,sexual abuse of children,sexual assault,sodomy,theft,weapon possession or sale
0,0,1805,murder,100.00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1843,murder,100.00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1855,murder,100.00,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,1863,murder,100.00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,1872,murder,100.00,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,177,2017,arson,0.75,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
177,41,1978,rape,100.00,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
178,41,1978,rape,100.00,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
179,41,1978,rape,75.00,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
180,41,1978,rape,75.00,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [196]:
from  sklearn.preprocessing import StandardScaler
numeric_cols = ['Date of the Crime' , 'Punishment for a crime']
scaler = StandardScaler()


df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [204]:
df = df.drop(['Type of the Crime', 'Legally Exonerated Encoded'], axis=1)

In [206]:
from sklearn.cluster import KMeans
wcss = []
for n in range(1, 11):
    kmeans = KMeans(n_clusters=n, init='k-means++', random_state=42)
    kmeans.fit(df)
    wcss.append(kmeans.inertia_)

ValueError: Input X contains NaN.
KMeans does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [207]:
df[df.isna().any(axis=1)]

,Unnamed: 0,Date of the Crime,Punishment for a crime,armed robbery,arson,assault,attempted murder,breaking and entering,burglary,carjacking,...,rape,robbery,sabotage,satanic ritual sex abuse,sexual abuse,sexual abuse of children,sexual assault,sodomy,theft,weapon possession or sale
7,7,-2.528392,NaN,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,9,-2.352759,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,50,-0.010997,NaN,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
51,52,-0.010997,NaN,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
70,71,0.106091,NaN,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
78,79,0.135363,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,100,0.252451,NaN,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
109,110,0.310995,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
173,174,1.072068,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0